### ISSUE TITLE
is there a way to know what pieces have been downloaded by p2p or http for debugging?

### ISSUE THREAD

**Issue by pavelm89** [Novage/p2p-media-loader#1]
is there an easy way to debug and find out the source of the file if it came from p2p or http

**Comment by mrlika** [comment]
Hi,

To enable ALL debugging please type in your browser console
```js
localStorage.debug = 'p2pml:*'
```
and reload the Web page.

You can enable only P2P logs like:
```js
localStorage.debug = 'p2pml:media-peer'
```
You can use events and track bytes that were downloaded over P2P and HTTP (see [demo](https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-demo/index.html#L290)):

```js
this.engine.on(p2pml.core.Events.PieceBytesDownloaded, this.onBytesDownloaded.bind(this));
this.engine.on(p2pml.core.Events.PieceBytesUploaded, this.onBytesUploaded.bind(this));
```

**Comment by pavelm89** [comment]
@mrlika  thanks alot for the reply , i did manage to make it work and i see alot of peers exchange info and data so i think im good. :)
