### ISSUE TITLE
Wrong JWPlayer provider & General player issues

### ISSUE THREAD

**Issue by Yokutto** [Novage/p2p-media-loader#10]
Hi, I tried to create a jwplayer instance in HLS with P2P, but it does not seem to work. In my tests the HLS is always loaded by the "provider.hlsjs.js" (default hls script of jwplayer), in the demo example i see that the segments are loaded by the initiator "p2p-media-loader-hlsjs.min.js". I can not see the difference between the test I did and the demo, could anyone explain what I did wrong?

Demo: https://jsfiddle.net/gkob21fv/1/
Browser: Chrome 70 win10

**Comment by mrlika** [comment]
"@hola.org/jwplayer-hlsjs" is not initialized. You have to add https://cdn.jsdelivr.net/npm/hls.js@latest script.

Then in a browser's console you will see 'init hola/hls provider v0.0.79 hls v0.11.0' message. It means that the provider is initialized.

**Comment by Yokutto** [comment]
Thanks, that worked.

Another question, I have some configurations from my old HLS provider and I would like to make some changes to the P2P configuration (like changing the tracker). But I could not change the default settings for HLS and P2P. Can you give me a little help with that? I do not have an intermediate knowledge in javascript
I read the explanation at https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-core#p2p-media-loader-core, but I did not quite understand

**Comment by mrlika** [comment]
You have to configure P2P Hls.js Engine instance like this:

```JS
var engine = new p2pml.hlsjs.Engine({
  loader: {
    trackerAnnounce: [ "wss://tracker1.xyz/", "wss://tracker2.com/" ]
  }
});
```
Engine configuration documentation:
https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-hlsjs#engine--new-enginesettings

HybridLoader settings documentaion (i.e. `loader` section of `settings` object):
https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-core#loader--new-hybridloadersettings

**Comment by Yokutto** [comment]
Thank you, your help is very appreciated :)

**Comment by Yokutto** [comment]
I reopened this to ask one more info.
How can I get the player to give more buffering (up to 60 seconds of video)? After I implemented the script, I noticed that at the beginning of the video buffering can not get past 1 second, and sometimes this causes a "lag" even without having problems with server-user.

I'm using this: 
`p2pml.hlsjs.initJwPlayer(player, {
	maxBufferSize: 100*1000*1000,
	maxBufferLength: 300,
	maxMaxBufferLength: 500,
	loader: engine.createLoaderClass()
});`

but it does not seem to have any effect

**Comment by mrlika** [comment]
You have to use [liveSyncDuration](https://github.com/video-dev/hls.js/blob/master/docs/API.md#livesyncduration) parameter of Hls.js playback engine. It is in seconds.

p2pml.hlsjs.initJwPlayer(player, {liveSyncDuration: 60, loader: engine.createLoaderClass() });

**Comment by Yokutto** [comment]
Nothing changed :/

**Comment by Yokutto** [comment]
It seems that the script is using the standard HLS settings of jwplayer (with very low buffer). But by the console, who is loading the segments is the "p2p-media-loader-hlsjs.min.js"

![image](https://user-images.githubusercontent.com/16729837/48256882-134ce080-e3f8-11e8-9641-bcfb870601bd.png)

**Comment by mrlika** [comment]
Most likely buffering issues are related to Hls.js engine itself.

You have to test it with raw Hls.js without P2P and player integrations. And if it doesn't work as expected report issues to [Hls.js](https://github.com/video-dev/hls.js) project.

You can use this fiddle as the base for your testing: https://jsfiddle.net/yhLnqu3t/

**Comment by Yokutto** [comment]
I get this result running only hls.js, without P2P script. I think "p2p-media-loader-hlsjs.min.js" is not interpreting the hls.js settings. The settings of the script itself work (such as changing the tracker), only the hls.js settings have no effect.
![image](https://user-images.githubusercontent.com/16729837/48257660-409a8e00-e3fa-11e8-942e-2494a46cc35b.png)

**Comment by Yokutto** [comment]
I make this fiddle if you want to view what i'm saying: https://jsfiddle.net/hmyapb2n/1/

**Comment by Yokutto** [comment]
No results. Something is stucking "maxBufferLength" to 30 seconds, like the jwplayer default hls provider. In console, the config is showed as expected. But in player don't work :/
https://jsfiddle.net/hmyapb2n/2/

**Comment by Yokutto** [comment]
I see other issue here. When the jwplayer is configured to show ads with VAST (not tested with google IMA), the player dies with error "Error in "time" event handler: TypeError: Cannot convert undefined or null to object". The player also does not save the quality and audio settings, and I saw that in later versions the subtitles also do not work as they should. Apparently these problems are from the holajs provider. Is there any way to use another HLS provider?

Advertisement test: https://jsfiddle.net/hmyapb2n/4/

**Comment by mrlika** [comment]
Looks like the problems go from hola HLS provider.

P2P Media Loader supports hls.js and Shaka Player playback engines. We can integrate with players that use one of these playback engines built-in or via a plugin.

In the case of JWPlayer we found only this plugin that works via hls.js

**Comment by thenikin** [comment]
Hi Yokutto, how do you check if liveSyncDuration setting is applied? I just tried mrlika's example and it worked. But would like to see what you're getting and how did you solve it if you did?

thanks

**Comment by mrlika** [comment]
Can't reproduce the issue - JWPlayer requires a paid plan to display VAST. Open source JWPlayer has no VAST support.
