### ISSUE TITLE
Desktop Safari freeze at the startup

### ISSUE THREAD

**Issue by xmugenx** [Novage/p2p-media-loader#100]
Safari freeze at the first peer, it will not freeze when create new peers but will not download anything from other peers.
tried with jwplayer from big demo  when playing this m3u8.
https://dapian.video-yongjiu.com/20190901/9943_6699ca5d/index.m3u8

other player freeze no matter how many peers

**Comment by mrlika** [comment]
The issue is in hls.js engine. The video plays well in ShakaPlayer engine in Safari. I reported it to hls.js engine repository.

**Comment by mrlika** [comment]
The bug is confirmed by hls.js team
