### ISSUE TITLE
WebRTC setRemoteDescription Deprecated

### ISSUE THREAD

**Issue by mrcolak** [Novage/p2p-media-loader#104]
Hello,

There is a deprecated (possibly removed) function on the core. When that function called, player fails and throw error. I don't know when and why that function needed to be called but I know that it is not working for sure.

https://cdn.jsdelivr.net/npm/p2p-media-loader-core@latest/build/p2p-media-loader-core.js
Line: 8573

https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setRemoteDescription#Deprecated_syntax

![image](https://user-images.githubusercontent.com/9140369/68548714-fa0eb380-0400-11ea-9105-0b56adf2ed35.png)

Regards.

**Comment by mrlika** [comment]
The function is not deprecated. The issue is that it is called on undefined value. Do you know a way to reproduce the issue?

**Comment by mrlika** [comment]
The bug is most likely in [simple-peer](https://github.com/feross/simple-peer) or [bittorent-tracker](https://github.com/webtorrent/bittorrent-tracker) NPM modules. If I can reproduce it I will create a bug report.
