### ISSUE TITLE
nginx secure link

### ISSUE THREAD

**Issue by raestrada95** [Novage/p2p-media-loader#105]
Hi, I would like to know if anyone has experience using secure link?, my m3u8 files have this structure
/videos/80e2dfecb5f54513ad4e2e6217d36fd4/hls/bunny.m3u8

But they can't connect because the token changes, if I open 2 videos using the same token it works perfectly. I talked to a company that sells cdn p2p services and they told me that it could be used without problem. I suppose it is some additional configuration that would have to be done in the tracker but I have no ides, I appreciate if someone could get me hot on the subject.

Thanks in advance for any assistance!.

**Comment by ckcr4lyf** [comment]
You can use some custom code for the part where segments are loaded over HTTP (XHR). Take a look here:

https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-core/README.md#loader--new-hybridloadersettings

Would need some programming from your side.

P.S. - Is the company an alternative to using p2p-media-loader? Or is the CDN company using this library and you're figuring out how to set it up? Curious since this an open source library after all.

**Comment by mrlika** [comment]
I think you should manually set swarm ID for your streams. Check the [FAQ](https://github.com/Novage/p2p-media-loader/blob/master/FAQ.md#what-are-the-requirements-to-share-a-stream-over-p2p).

**Comment by raestrada95** [comment]
swarm ID 

> You can use some custom code for the part where segments are loaded over HTTP (XHR). Take a look here:
> 
> https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-core/README.md#loader--new-hybridloadersettings
> 
> Would need some programming from your side. It would be best if you can clarify a bit more as to what kind of a "secure" link it is, authentication mechanism etc.
> 
> P.S. - Is the company an alternative to using p2p-media-loader? Or is the CDN company using this library and you're figuring out how to set it up? Curious since this an open source library after all.

Thanks for the help, not the other company does not use this library but since the technology is the same, that's why I asked them.

**Comment by raestrada95** [comment]
Thanks for the help I think if it works, I will do the test and tell you if it worked.

**Comment by raestrada95** [comment]
> I think you should manually set swarm ID for your streams. Check the [FAQ](https://github.com/Novage/p2p-media-loader/blob/master/FAQ.md#what-are-the-requirements-to-share-a-stream-over-p2p).

Thanks for the help I think if it works, I will do the test and tell you if it worked.
