### ISSUE TITLE
Jwplayer subtitles no work

### ISSUE THREAD

**Issue by marcofbb** [Novage/p2p-media-loader#106]
Hi,
I am having trouble activating P2P with JWplayer VTT subtitles from the player setup.

I tried to fix it but I couldn't find the solution, I'm new to hls.js and got lost in the calls.

Could you help me?

Test: http://marcobiondi.com.ar/test.php

**Comment by mrlika** [comment]
Yes, VTT subtitles specified this way don't work with `jwplayer-hlsjs` plugin. But you can add VTT subtitles directly to your .m3u8 manifest, then hls.js will take care of the subtitles handling. See the example: http://novage.com.ua/p2p-media-loader/demo.html?url=https%3A%2F%2Fstorage.googleapis.com%2Fshaka-demo-assets%2Fangel-one-hls%2Fhls.m3u8&type=jwplayer

**Comment by marcofbb** [comment]
Hi,
What would I have to consider to create a dynamic .m3u8 (blob url) that automatically reads my .m3u8 and the subtitle, and generates the new .m3u8 (blob url) for hls?

The interesting thing is that in jwplayer 8.0.x if the VTT or SRT subtitles work

**Comment by mrlika** [comment]
JWPlayer logic is:

If VTT subtibles are not specified in .m3u8 file JWPlayer processes them without hls.js
If VTT are specified in .m3u8 they are processed by hls.js

And I currently don't know how to enable processing of such external VTT subtitles by JWPlayer in 
`jwplayer-hlsjs` module: https://github.com/Novage/jwplayer-hlsjs

**Comment by afdah** [comment]
After running some tests, here is what i figure out:
On standalone jwplayer, 
if i specify both external and in the m3u8 file, the m3u8 file will be ignored. The external will be processed. Meaning, external is more priority over m3u8.

On jwplayer-hljs,
if I specify both external and in the m3u8 file, jwplayer-hlsjs will display both selections in the captions menu. 
However, only the hls subtitles will be displayed if i choose the hls version. 
If i choose the external version, it is not displayed on desktop. 
The external version can only be displayed on ios safari where native hls is present and hlsjs is not used.
I tried enableWebVTT: false for hlsjs, the vtt track in m3u8 is ignored, but the external track still unable to display on desktop.

**Comment by marcofbb** [comment]
> Después de ejecutar algunas pruebas, esto es lo que descubrí:
> en jwplayer independiente,
> si especifico tanto externo como en el archivo m3u8, el archivo m3u8 será ignorado. Lo externo será procesado. Es decir, externo es más prioridad sobre m3u8.
> 
> En jwplayer-hljs,
> si especifico tanto externo como en el archivo m3u8, jwplayer-hlsjs mostrará ambas selecciones en el menú de subtítulos.
> Sin embargo, solo se mostrarán los subtítulos hls si elijo la versión hls.
> Si elijo la versión externa, no se muestra en el escritorio.
> La versión externa solo se puede mostrar en ios safari donde está presente hls nativo y no se usa hlsjs.
> 
> Intenté enableWebVTT: falso para hlsjs, la pista vtt en m3u8 se ignora, pero la pista externa aún no se puede mostrar en el escritorio.

Yes, for my Jwplayer he made changes to his code and the HLS hola is old, using an old JWplayer everything works correctly.

**Comment by marcofbb** [comment]
A quick solution would be to generate the .m3u8 through javascript, adding the subtitles in format accepted by HLS

**Comment by afdah** [comment]
> A quick solution would be to generate the .m3u8 through javascript, adding the subtitles in format accepted by HLS

HLS webvtt is segmented. It needs to be generated with the source using ffmpeg or other tools.

Based on JWPlayer release notes I have tested, the latest version to work with external subtitles is v8.2.0. A quick solution is to use v8.2.0. 
https://www.jwplayer.com/release-notes/jw-player/

v8.2.2 includes "Fixed an issue with captions not working in 360 videos in Safari". This version onwards, external subtitles do not work.
