### ISSUE TITLE
Discussion: Can this technology be used in APP development

### ISSUE THREAD

**Issue by lxalano** [Novage/p2p-media-loader#108]
Discussion: Is it possible to support native Android development or iOS software in some way?

**Comment by mrlika** [comment]
* You can use the technology in WebView (or similar) in Android.
* Unfortunately, UIWebView and Safari on iOS don't support the required APIs for media payback.
* iPadOS supports the APIs so probably it will work in UIWebView on iPads.
* On iOS you can try to embed P2P library into https://github.com/google/shaka-player-embedded that brings V8 engine to iOS

**Comment by X-Kent** [comment]
There are commercial solutions that do very similar stuff on Android/Apple devices on the native level so you don't need to change your player/app/anything but they are non-free other than a limited trial.

**Comment by snowinszu** [comment]
Here is a commercial solution: https://docs.cdnbye.com/#/en/android/introduction

**Comment by X-Kent** [comment]
Here is another one https://www.peerplug.net/ those are new kids on the block but offer simple integration and specialize in apps.

**Comment by Anil-matcha** [comment]
Here is a solution available for apps with native integration which I found. 

https://github.com/PeerVadoo-tv/android-sdk
