### ISSUE TITLE
Offline Playback

### ISSUE THREAD

**Issue by afdah** [Novage/p2p-media-loader#109]
Currently offline playback works when the segment urls are fixed.
But when the segment urls keep changing, but pointing to the same content, hls does not work although segments: { swarmId: "unique string" } has been set.

I can see storage works and stored segments are being sent through p2p but the the player is not working. No error code, seems like the player is hang.

I believed the original request/response urls are being checked when retrieving the segments from storage by hls.
P2P module works. I guess the original request/response urls are not checked when retrieving segments from storage?

Below is the fixed url segments demo taken from your code.
Currently i'm unable to provide demo for changing url segments.

https://jsfiddle.net/4aL8bw6g/

Taken from

https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-hlsjs/demo/offlineplayback.html

**Comment by afdah** [comment]
My bad. It is working.

At times it does not work. I'm not sure whether it is indexedDB or hlsjs.
When it does not work, player will hang.

I already set localStorage.debug = '*' at the console and debug: true for hlsjs
No error message.

When i disable custom segmentsStorage, the player will work. So there is nothing wrong with media playing.

Is there some kind of check when getting the segments from indexedDB?
From log, i can see getSegment returns successfully.
It is just the player refuse to play.

The only problem i can think right now is probably the media. As i'm playing aes-128 encrypted hls, the key could have change when refreshing the page and so the current segments stored in indexedDB could not be decrypted. I expect to see error from hlsjs if this happens.

**Comment by afdah** [comment]
If i can see error from hlsjs regarding error decrypting segment, than my suspect is correct.
The new playlist contains different key and the current stored segments is invalid for offline play.

As i already set { swarmId: "unique string" }, p2ml assumes content is the same.

By the way, my scenario is VOD and the urls keep changing although it is the same content. I will see dozens of playlists at IdbAssetsStorage if I keep on refreshing the page. For this, i will need to disable P2P as everyone in the swarm is receiving different keys with different segments.

Probably i will need a custom segmentValidator as well for this scenario.

**Comment by mrlika** [comment]
The segments are stored encrypted. You can't decrypt them using different key.

**Comment by afdah** [comment]
Yes, you are right. For my VOD scenario, after investigation i found out that there are several copies of the same content being distributed with different aes-128 key. Unless the segments data are saved with aes-128 key, there is no way to play the segments.
