### ISSUE TITLE
A way that can improvement this library 

### ISSUE THREAD

**Issue by Er-rchydy** [Novage/p2p-media-loader#11]
One improvement that can be made is to force the player to start downloading and playing the first segment instead of the last one or the one before. 
That can lead to latency problems but that's not a big issue i guess , if the playlist have 6 segments, 10 seconds each, if you force the player to start from the first segment, that gives the `P2P-media-loader` enough time (50 seconds) to download the rest segments through  P2P, instead of downloading the last one or the one before (gives the library 10 to 20 seconds to download the next segment through P2P).
there is no way to do that in `Clappr` as i know, the only work around i found is to seek back he first segment like this: 
```
events: {
                    onPlay: function() {
                    if (player._hasSeek) {
                        return
                    }
                    player.seek(0);
                    player._hasSeek = true;
                    },
                } 
```
i don't know about other players, i hope there are a way to force the player to download and play the first segment. and add that option to this library so we can configure what segment that can be download first. so if latency is important to someone then he can choose the last segment, and if it's not an issue he can choose the first one and give enough time to `P2P-media-loader` to download the max segments through P2P.
thanks a lot for this amazing library

**Comment by mrlika** [comment]
It is already configurable.

Segment index that Hls.js engine requests for playback at the very beginning is controled by its [configuration](https://github.com/video-dev/hls.js/blob/master/docs/API.md#livesyncdurationcount): liveSyncDurationCount, liveSyncDuration, liveMaxLatencyDurationCount, liveMaxLatencyDuration.

You can configure these parameters for Clappr using [hlsjsConfig](https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-hlsjs#initclapprplayerplayer) configuration property.
