### ISSUE TITLE
Trackers Graph Only show from same IP/Computer

### ISSUE THREAD

**Issue by kangdulba** [Novage/p2p-media-loader#110]
hi can you tell me why tracker only works or only captures signals only from the same computer, and does not provide data from other computers / devices.

Suppose I open my computer and I ask my friend to open the same link (from another location/IP) then what happens is the graph does not send data from my friend's computer, but when I click on a new peer, the signal will send a response if there is a new peer.
even though I've made a unique swarm id for each video

`segments: {
                    swarmId: 'video-uniqueID'
                }`

**Comment by mrlika** [comment]
Not all peers can connect with each other over WebRTC. It depends on network configuration, browsers compatibility, etc. If you both behind incorrectly configured NAT most likely you will not be able to connect. Can you connect with a peer from the same LAN?

**Comment by kangdulba** [comment]
yes I can connect with the same LAN, but when I open it on another computer (rdp for example) or I tell my friend a different ip when I check that no peer entered my video player

**Comment by mrlika** [comment]
Then it is OK. Not all peers can connect. Like in BitTorrent.

**Comment by Teranode** [comment]
you're best best is to add a TURN server for those instances, cause that's what they were meant to handle

**Comment by mrlika** [comment]
No need in TURN server, you always have CDN.

With TURN server traffic will go: CDN -> peer1 -> TURN -> peer2.

Considering that TURN traffic is paid - you have to buy or support your own TURN servers infrastructure it is 2 times cheaper for peer2 to download directly from CDN if it can't connect with peer1.
