### ISSUE TITLE
P2P not working with secure link with session IP

### ISSUE THREAD

**Issue by Alexdrr** [Novage/p2p-media-loader#113]
Hello! I did kaltura-securelink from akamai-token script. Also i selected swarmid and that works ok, but any IP can stream/download video. If I put limitation session by IP, then stream/download can only 1 IP, but P2P not working and every user download video from server without P2P. If i remove checking IP from securelink session then P2P works again, but URL can use eny IP.
Can you help pls, how i can use session IP limitations in securelink and working P2P?

**Comment by afdah** [comment]
It should work unless kaltura-securelink break something when inserting ip limitation token in the m3u8 playlist. I use the same thing, the only difference is i did not limit ip address. Only time based token. Meaning the url is only valid for some time.

**Comment by Alexdrr** [comment]
do you use akami token + path encryption?

**Comment by afdah** [comment]
> do you use akami token + path encryption?

yes, but i did not include user ip address to generate the akamai token

**Comment by pedro0606** [comment]
> Hello! I did kaltura-securelink from akamai-token script. Also i selected swarmid and that works ok, but any IP can stream/download video. If I put limitation session by IP, then stream/download can only 1 IP, but P2P not working and every user download video from server without P2P. If i remove checking IP from securelink session then P2P works again, but URL can use eny IP.
> Can you help pls, how i can use session IP limitations in securelink and working P2P?

i have solution for it, ping me

**Comment by afdah** [comment]
> > Hello! I did kaltura-securelink from akamai-token script. Also i selected swarmid and that works ok, but any IP can stream/download video. If I put limitation session by IP, then stream/download can only 1 IP, but P2P not working and every user download video from server without P2P. If i remove checking IP from securelink session then P2P works again, but URL can use eny IP.
> > Can you help pls, how i can use session IP limitations in securelink and working P2P?
> 
> i have solution for it, ping me

Post the solution here please.

**Comment by pedro0606** [comment]
contact me via email peer9pro@gmail.com
