### ISSUE TITLE
Logging ResponseUrl onSegmentError

### ISSUE THREAD

**Issue by afdah** [Novage/p2p-media-loader#114]
Here i can get responseurl onSegmentError successfully.
Consider the below sceneario.
p2pml make a options segment request
receive 200 response
p2pml make a get segment request
receive 302 response redirecting to another url
p2pml make a new options segment request
receive 200 response
p2pml make a new get segment request
receive 403 response

Now, I'm getting a blank responseUrl onSegmentError.
Consider the below scenerio.
p2pml make a options segment request
receive 200 response
p2pml make a get segment request
receive 302 response redirecting to another url
p2pml make a new options segment request
receive 403 response
Thats it. responseurl is blank as p2pml did not make a 2nd get request as 2nd options request returns a 403 error.
How do I capture that 302 url also known as responseurl onSegmentError?

**Comment by mrlika** [comment]
`XMLHttpRequest` is used. It does all the redirects. If the response URL is empty then most likely it should be so. The code that gets responseURL on error:

```typescript
private segmentFailure(segment: Segment, error: any, xhr: XMLHttpRequest) {
    segment.responseUrl = xhr.responseURL === null ? undefined : xhr.responseURL;

    this.xhrRequests.delete(segment.id);
    this.failedSegments.set(segment.id, this.now() + this.settings.httpFailedSegmentTimeout);
    this.emit("segment-error", segment, error);
}
```

**Comment by afdah** [comment]
I guess the only way is to handle this server side.
Instead of depending responseURL, I need to make do with requestURL onSegmentError log to server.
