### ISSUE TITLE
Can you make a full sample code for JwPlayer?

### ISSUE THREAD

**Issue by duykma2** [Novage/p2p-media-loader#115]
Can you make a html example for Jwplayer like you did with Clappr?
``
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Clappr/Hls.js with P2P Media Loader</title>
    <meta charset="utf-8">
    <script src="https://cdn.jsdelivr.net/npm/p2p-media-loader-core@latest/build/p2p-media-loader-core.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/p2p-media-loader-hlsjs@latest/build/p2p-media-loader-hlsjs.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/clappr@latest"></script>
</head>
<body>
    <div id="player"></div>
    <script>
        if (p2pml.hlsjs.Engine.isSupported()) {
            var engine = new p2pml.hlsjs.Engine();

            var player = new Clappr.Player({
                parentId: "#player",
                source: "https://akamai-axtest.akamaized.net/routes/lapd-v1-acceptance/www_c4/Manifest.m3u8",
                mute: true,
                autoPlay: true,
                playback: {
                    hlsjsConfig: {
                        liveSyncDurationCount: 7,
                        loader: engine.createLoaderClass()
                    }
                }
            });

            p2pml.hlsjs.initClapprPlayer(player);
        } else {
            document.write("Not supported :(");
        }
    </script>
</body>
</html>`

Thanks!

**Comment by duykma2** [comment]
@mrlika  I tried this demo but it doesn't work.
Please advice. Thanks!
https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-hlsjs/demo/jwplayer.html
http://ustvgo.services/test.html

**Comment by mrlika** [comment]
JWPlayer is in the demo and examples: https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-hlsjs/demo/jwplayer.html

**Comment by mrlika** [comment]
Your JWPlayer configured to include compatibility script. You can see it in https://content.jwplatform.com/libraries/1PhFDXig.js file:
```
/*
    This script is a compatibility bridge between our new API, introduced in JW8, and our old API. Our new API removes
    several methods and properties and may break any scripts interacting with the new player. We provide this script to
    you so that you can upgrade to the latest & greatest immediately; however, we encourage you to read through this source,
    upgrade your usage of our API, and remove this bridge. It will save your page some time & space.
 */
(function(playerLibrary) {
...
```
Disable this compatibility script in JWPlaye admin and it will work.
