### ISSUE TITLE
Hope the loader can support fetch loading

### ISSUE THREAD

**Issue by hkchenhongyi** [Novage/p2p-media-loader#116]
Hope the loader can support fetch loading

**Comment by mrlika** [comment]
If you mean [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) then I think it possible to implement all the requirements (automatic redirects and receive chunked data while downloading) with fetch but I don't know what advantages will it give.

**Comment by hkchenhongyi** [comment]
It supports more parameters! I can use the mode parameter to do no-cors, bypassing some verification

> If you mean [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) then I think it possible to implement all the requirements (automatic redirects and receive chunked data while downloading) with fetch but I don't know what advantages will it give.

It supports more parameters! I can use the mode parameter to do no-cors, bypassing some verification

**Comment by mullerivan** [comment]
you can check how to solve this problem on your server side  on https://swarm.video/#/home

cheers
