### ISSUE TITLE
Segment Identification

### ISSUE THREAD

**Issue by defrinex** [Novage/p2p-media-loader#12]
Hello,

First of all, thanks for this awesome open source.

My m3u8 file url and all segments links are different for each user.

I believe peer system is identify which peer connect to which by segment or m3u8 links. But its not able to do it correctly because all users got a different m3u8 and segment links.

Is there any way to make a manuel match?

Something like this;

```
fileLinkReplace: function (url) {
   url = remove_unique_parts(url);
   return url;
}
```

```
segmentIdReplace: function (level, sn, url) {
   url = remove_unique_parts(url);
   return url;
}
```

from

> https://example.com/hls/baxppq2zn5ts5n2gmlloot52i6lyz5rcvhjiszq4vsemf5jdqxwulk7bcxha/seg-27-v1-a1.ts

to

> https://example.com/hls/videoid352352/seg-27-v1-a1.ts

**Comment by mrlika** [comment]
Hi,

By analyzing P2P Media Loader use cases we see that this is one of the features that is most required. And I think we will implement it next week.

You will be able to specify stream ID like:

```JS
var engine = new p2pml.hlsjs.Engine({
  loader: {
    streamId: 'https://example.com/hls/videoid352352'
  }
});
```
By default, stream ID will be equal to stream manifest URL without query string as it works now. But you can change it to any other string using this parameter.

It should allow sharing of the same streams that are:

1) hosted under different protocols (i.e. HTTP, HTTPS):

   http://sample.com/stream.m3u8
   https://sample.com/stream.m3u8

2) under different domains:

   http://us.sample.com/stream.m3u8
   http://eu.sample.com/stream.m3u8
   http://jp.sample.com/stream.m3u8

3) under different URLs:

   https://sample.com/stream-secret-key1.m3u8
   https://sample.com/stream-secret-key2.m3u8

TS segments URLs do not matter if you have #EXT-X-MEDIA-SEQUENCE tag in your manifest.

**Comment by defrinex** [comment]
Its awesome to hear this! Thank you very much. Looking forward to it.

**Comment by defrinex** [comment]
Hey, any news with this feature?

**Comment by mrlika** [comment]
Good news! I am working on it now :-)

**Comment by mrlika** [comment]
Implemented in version 0.2.0 like:

```JS
var engine = new p2pml.hlsjs.Engine({
  segments: {
    swarmId: 'custom swarm ID'
  }
});
```

**Comment by mrlika** [comment]
Also you can use 'swarm' query URL parameter in the demo like:

https://novage.com.ua/p2p-media-loader/demo.html?url=https%3A%2F%2Fwowza.peer5.com%2Flive%2Fsmil%3Abbb_abr.smil%2Fplaylist.m3u8&type=clappr&swarm=test_swarm

But please note, the parameter is not applied if you press 'Apply' or 'Create new peer' button.

**Comment by defrinex** [comment]
Thank you very much! It's working like a charm.

![image](https://user-images.githubusercontent.com/9140369/48644646-4bee4a80-e9f4-11e8-816d-d948cd6469ed.png)

**Comment by renatofrota** [comment]
> Also you can use 'swarm' query URL parameter in the demo like:
> 
> https://novage.com.ua/p2p-media-loader/demo.html?url=https%3A%2F%2Fwowza.peer5.com%2Flive%2Fsmil%3Abbb_abr.smil%2Fplaylist.m3u8&type=clappr&swarm=test_swarm
> 
> But please note, the parameter is not applied if you press 'Apply' or 'Create new peer' button.

Just for information to those reading this old thread, this hidden feature is not available in current demo (the swarm ID is automatically - and always - set to stream src URL with scheme without query string).
