### ISSUE TITLE
How to manually set swarm ID for url with hotlink protection?

### ISSUE THREAD

**Issue by duykma2** [Novage/p2p-media-loader#123]
My url like this:
https://somecdn.com/mystream_12345.m3u8?nimblesessionid=42893822&wmsAuthSign=c2VydmVyX3RpbWU9My8xOC8yMDIwIDU6MTQ6MDQgQU0maGFzaF92YWx1ZT1MeTZmeXVqNXBBTC9YNmRSWVZSRnF3PT0mdmFsaWRtaW51dGVzPTI0MCZpZD0w

How should I manually set swarm ID for this url format?

**Comment by mrlika** [comment]
Check FAQ: https://github.com/Novage/p2p-media-loader/blob/master/FAQ.md#how-to-manually-set-swarm-id

In your case swarm ID can be `https://somecdn.com/mystream_12345.m3u8` or any other unique to a stream string identifier.
