### ISSUE TITLE
Nodejs server ts files p2p.

### ISSUE THREAD

**Issue by hpcarlos** [Novage/p2p-media-loader#125]
is it possible to create a nodejs server on the server side, so that the server itself can also announce and send to clients via p2p as well?

It would be like this:

The client connects and downloads the first 2 segments via http.
Then the server can also provide to clients via p2p, even if it doesn't have another client in the same stream.

The server would provide the .ts via http and also via p2p.
and download what is best for the client, if the meso has any limitation problem via http.

**Comment by mrlika** [comment]
Node.js by default has no WebRTC. If yo install a WebRTC module that supports data channels API then most likely it should s possible
