### ISSUE TITLE
loading segments from two different servers in parallel.

### ISSUE THREAD

**Issue by supersh86** [Novage/p2p-media-loader#126]
Hi, is it possible to specify 2 parallel servers(swarm) for downloading video?

**Comment by mrlika** [comment]
You can check `segmentUrlBuilder` parameter: https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-core#loader--new-hybridloadersettings

It allows to modify the segment URL before the request. It means you can for example randomly change domain name thus request in parallel from 2 different locations.

**Comment by supersh86** [comment]
Do I need to customize a segment or playlist link?
