### ISSUE TITLE
It is normal to have so many leeching but no one is seeding?.

### ISSUE THREAD

**Issue by jhemmmm** [Novage/p2p-media-loader#128]
Hello,

There's currently 100 clients base on my webtracker stats. It says. They are only leecher but no one is seeding. I am doing it right?.

**Comment by mrlika** [comment]
There are no leachers and seeders in P2P Media Loader swarms. All users are just peers.

The library supports live streams. There can be no seeders when sharing live stream.

**Comment by jhemmmm** [comment]
Great. Thanks. I though it wasn't working well.
