### ISSUE TITLE
React native integration

### ISSUE THREAD

**Issue by shell1986** [Novage/p2p-media-loader#130]
Hello everyone, how do you think integration with react native is possible?

**Comment by mrlika** [comment]
React native has WebRTC Data Channels support using the module: https://github.com/react-native-webrtc/react-native-webrtc.

But I can't find the support of Hls.js or Shaka Player engines because of missing Media Source Extensions API implementation.

**Comment by supersh86** [comment]
Hls support is available at https://github.com/react-native-community/react-native-video

I want to start by downloading the video from the source, and then think about how to play it.
Can you give general recommendations?

**Comment by mrlika** [comment]
Its a <Video> component. It has no MSE support or similar. 

Paid solution implement P2P engine as a local small proxy server. A video player can request a stream from this local proxy.

Probably such proxy can be implemented in JS using React Native and even reuse code from this project.

**Comment by supersh86** [comment]
Paid solution?

**Comment by mrlika** [comment]
Yes, paid P2P video delivery solutions similar to this one, but they also support Android and iOS. You can easily Google them.

**Comment by supersh86** [comment]
I thought you had a paid version.
