### ISSUE TITLE
Usage in a video commerce startup like Tiktok

### ISSUE THREAD

**Issue by Anil-matcha** [Novage/p2p-media-loader#132]
Does it make sense to use this technology in a video app like Tiktok having short byte sized videos around 1 minute.

Because the peers get created and destroyed every other video we might not have reliable connections to share content with other peers. It makes sense for OTT content having size of around 1 hour videos.

I am planning to open a video app like Tiktok with small videos, so want your suggestion about it.

**Comment by mrlika** [comment]
It takes time to get and connect to peers. If in your use case visitors spend less then 1 minute on each video then most likely it has no sense.

**Comment by Anil-matcha** [comment]
Thanks @mrlika for letting me know.
