### ISSUE TITLE
Demo is not showing any peers at all

### ISSUE THREAD

**Issue by xoraingroup** [Novage/p2p-media-loader#134]
Hi,

Demo: https://novage.com.ua/p2p-media-loader/demo.html

  We have tried, Google Chrome, Firefox, Safari and Brave browsers. The demo when started works fine locally and if we click on create new peer, we can see the peers. However I shared the same link with 2 of my other friends remotely and we were not able to see peers at all including us. It was shown just "You" and no other peers. Tried incognito window even but it didn't helped out. Tried "Apply" button as well but to no avail. Are we missing something ?

Thank you and we will be waiting for your kind reply. :)

**Comment by ckcr4lyf** [comment]
The ability to connect to peers is limited to some extent by firewalls. I've usually had decent luck on direct home connections, But if you're behind an enterprise grade firewall chances are that it blocks this kind of traffic / WebRTC peer connections. 

A way to "test" this is to use another WebRTC based service, such as https://file.pizza/ and see if the other person is able to download from you.

**Comment by mrlika** [comment]
It can be an issue with public trackers also(they are not reliable). It works now.
To run a stable solution you have to run your personal tracker.
