### ISSUE TITLE
p2pml.core.Segment is not a constructor

### ISSUE THREAD

**Issue by supersh86** [Novage/p2p-media-loader#135]
Hi, I decided to try loading segments via core
But in the end I got an error

test.html: 37 Uncaught (in promise) TypeError: p2pml.core.Segment is not a constructor

Here is an example code.

`

 <!DOCTYPE html>

<html>
<head>
	<title></title>
	<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/p2p-media-loader-core@0.6.2/build/p2p-media-loader-core.min.js"></script>
	<script type="text/javascript" src="js/m3u8-parser.min.js"></script>
</head>
<body>
<script type="text/javascript">
manifestA=""
fetch("https://test-streams.mux.dev/x36xhzz/url_6/193039199_mp4_h264_aac_hq_7.m3u8")  .then(response => response.text()).then(function(text) {
var parser = new m3u8Parser.Parser();
parser.push(text);
console.log(parser);
parser.end();
var parsedManifest = parser.manifest;
console.log(parsedManifest)
manifestA= parsedManifest;
return  startLoad(parsedManifest);
})

var loader = new p2pml.core.HybridLoader();
function startLoad(manifest){

loader.on(p2pml.core.Events.SegmentLoaded, function (segment) {
    console.log("Loading finished, bytes:", segment.data.byteLength);
});

loader.on(p2pml.core.Events.SegmentError, function (segment, error) {
    console.log("Loading failed", segment, error);
});
console.log("https://test-streams.mux.dev/x36xhzz/url_6/"+manifest.segments[0].uri);
loader.load([
 	new p2pml.core.Segment("segment-1", "https://test-streams.mux.dev/x36xhzz/url_6/"+manifest.segments[0].uri, undefined, 0),
    new p2pml.core.Segment("segment-2", "https://test-streams.mux.dev/x36xhzz/url_6/"+manifest.segments[1].uri, undefined, 1),
    new p2pml.core.Segment("segment-3", "https://test-streams.mux.dev/x36xhzz/url_6/"+manifest.segments[2].uri, undefined, 2)
], "swarm-1");

}
</script>
</body>
</html>

`

**Comment by mrlika** [comment]
Segment is just a type definition in TypeScript. It doesn't exist in JavaScript. In JavaScript it is just an object:

```javascript
const segment = {
    id: 'segmentId',
    url: 'http://some/segment/url.ts',
    masterSwarmId: 'master swarm ID',
   ...
}
```

**Comment by supersh86** [comment]
I was guided by this example, what is my mistake?

https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-core#p2p-media-loader-core

**Comment by mrlika** [comment]
It looks like the example is outdated. We will fix it. The `Segment` is not a constructor. Replace it with a JavaScript object with required fields.

**Comment by supersh86** [comment]
Вы можете дать просто пример использования. Я не совсем понимаю 
Мне нужно сделать цикл и запрашивать в таком виде?
const segment = {
    id: 'segmentId',
    url: 'http://some/segment/url.ts',
    masterSwarmId: 'master swarm ID',
    ...
}

**Comment by supersh86** [comment]
`    	    var loader = new p2pml.core.HybridLoader();

        loader.on(p2pml.core.Events.SegmentLoaded, function(segment) {
            console.log("Loading finished, bytes:", segment.data.byteLength);
        });

        loader.on(p2pml.core.Events.SegmentError, function(segment, error) {
            console.log("Loading failed", segment, error);
        });
        loader.on(p2pml.core.Events.SegmentAbort, function(segment) {
            console.log("Loading ", segment);
        });
        console.log("https://test-streams.mux.dev/x36xhzz/url_6/" + manifest.segments[0].uri);

        segment0 = {
            id: 'segment-1',
            url: "https://test-streams.mux.dev/x36xhzz/url_6/" + manifest.segments[0].uri,
            masterSwarmId: 'undefined',
            priority: 0,
        }
        p=loader.load(segment0, "swarm-1");
        console.log(p);`
На данный момент у меня такая конструкция, но к сожалению я получаю только промес. Загрузка не происходит.

**Comment by mrlika** [comment]
loader.load требует масив сегментов. как минимум `loader.load([segment0], "swarm-1");`

https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-core#loaderloadsegments-streamswarmid
```
loader.load(segments, streamSwarmId)

Creates new queue of segments to download. Aborts all http and peer connections for segments that are not in the new load and emits Events.SegmentAbort event for each aborted event.

Function args:

    segments - array of Segment class instances with populated url and priority field;
    streamSwarmId - current swarm;

```

**Comment by supersh86** [comment]
Спасибо! получилось!
Еще один вопрос. 
Как мне узнать сколько сегментов скачано? 
В segmentsQueue я вижу полный список файлов.

**Comment by mrlika** [comment]
За этим надо следить в событиях

loader.on(Events.SegmentLoaded, function (segment, peerId) {})
loader.on(Events.SegmentError, function (segment, error, peerId) {})
loader.on(Events.SegmentAbort, function (segment) {})

**Comment by supersh86** [comment]
а streamSwarmId в loader.load это тоже самое что и swarmId в настройках segments?

**Comment by mrlika** [comment]
Нет. Это swarmId + порядковый номер стрима (для видео с несколькими качествами). Точно формат не помню.

**Comment by supersh86** [comment]
Спасибо! 
`masterSwarmId+'+V'+quality`
Добавил порядковый номер и получил p2p!
