### ISSUE TITLE
p2p just work on same ip

### ISSUE THREAD

**Issue by fluss45** [Novage/p2p-media-loader#136]
p2p work only on same network.otherwise it just use direct hls play.

can you tell me what we doing wrong

**Comment by ckcr4lyf** [comment]
It's likely that the firewall in your network setup is preventing peer to peer access. Can you try sharing a file between the two peers, using a website such as "https://file.pizza"?

**Comment by fluss45** [comment]
http://51.15.201.214:8081/static.html

**Comment by mrlika** [comment]
Not all peers can connect over WebRTC and it depends on browser, netwrok configuration (NAT) etc. It is true for any P2P network.
