### ISSUE TITLE
Update swarmId

### ISSUE THREAD

**Issue by renatofrota** [Novage/p2p-media-loader#139]
Is there a way to update the swarmId after manifest is loaded?

The information we want to use as swarmId is present in both:
- part of the 1st redirect URL; and
- part of the segments URLs

example:

- manifest is example.com/some/example/**123**.m3u8
- redirects to some.example.net/here/is/some/example/**123**.m3u8?token=asdf
- segments: /hlsr/a/random/string/here/**123**_999.ts

in this case, swarmId should remain the same.

but depending on some factors, it redirects to an alternate server:

- manifest is example.com/some/example/**123**.m3u8
- alternate.example.net/here/is/another/example/**456**.m3u8?token=asdf
- segments: /hlsr/other/random/string/here/**456**_999.ts

swarmId is set initially 123, we want to update it to 456 on the 2nd case.

Thanks in advance.

**Comment by mrlika** [comment]
No way to change it. But if the stream is the same on all alternate servers then you can use the same swarm ID. The main idea is all peers in the swarm share the same video data.

**Comment by renatofrota** [comment]
In this case, the streams are not exactly the same. We have managed it by fetching the stream URL with curl first and catching the redirect_url before inserting it to the player (and using the corresponding swarmId as well). Thank you.
