### ISSUE TITLE
Is it possible to create our own WebTorrent and STUN Server?

### ISSUE THREAD

**Issue by defrinex** [Novage/p2p-media-loader#14]

**Comment by Er-rchydy** [comment]
yes you can, for the Tracker [uWebTorrentTracker](https://github.com/DiegoRBaquero/uWebTorrentTracker), i'm not sure if it's a good idea about the STUN server, especially if you know that the STUN server used in `p2p-media-loader` is provided by Google.

**Comment by Er-rchydy** [comment]
In order for  a peers to communicate with each other, they need to know each other's IP and port number, but in most cases devices are behind of NAT (it gives them a local IP) and firewalls or antivirus that block certain ports . so what STUN server do is to discover the device public IP and port, it's like you ask him, hey STUN server what's my public IP address and he respond with your public IP address. then you move and use that public IP and port to communicate with other peers.

**Comment by mrlika** [comment]
There are few open source WebTorrent servers and many STUN servers available. You can run your own instances of the servers, configure P2P Media Loader to use them and create your private P2P cloud.

STUN is optional component but without it your peers most likely will not connect. It is used by browsers to do [ICE](https://en.wikipedia.org/wiki/Interactive_Connectivity_Establishment).

**Comment by mrlika** [comment]
Open source WebTorrent trackers: [bittorrent-tracker](https://github.com/webtorrent/bittorrent-tracker), [uWebTorrentTracker](https://github.com/DiegoRBaquero/uWebTorrentTracker)

**Comment by defrinex** [comment]
Thanks for the info!
