### ISSUE TITLE
[Question] Initial load without p2p

### ISSUE THREAD

**Issue by marcofbb** [Novage/p2p-media-loader#143]
Hello,
A question, how can I make the first 10 fragments not be served from P2P? Because it generates a slight delay in the initial load of the player

Thank you

**Comment by mrlika** [comment]
Hi,

You can play with [settings](https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-core#loader--new-hybridloadersettings), particularly `requiredSegmentsPriority`.

Here you can find an example of how to apply settings:
https://github.com/Novage/p2p-media-loader/blob/master/FAQ.md#how-to-achieve-better-p2p-ratio-for-vod-streams

**Comment by marcofbb** [comment]
Thanks,
One question, when I activate p2p the videos are mixed.

For example player one plays "Video A" and player two "Video B", fragments of video B appear in player one.

I had to deactivate it, what could it be? Video URLs are different for each video

**Comment by mrlika** [comment]
Swarm ID should be different for different streams. It equals stream URL without query parameters by default. If all your streams are served through the same URL with a difference in query parameters then you have to set `swamId` in configuration manually to be different for different streams and to be the same for the same streams.

**Comment by marcofbb** [comment]
Yes, the URLs are also different for each .ts file

Example https://ipfs.io/ipfs/QmNXZ7GxRxtxfvZQGasdd3rpGEsSM9vZQhZnW2/
https://ipfs.io/ipfs/Qm123xRxtxfvZQGa123pGEsSM9vZQhZ123122/


I will try what you say, thank you very much!
