### ISSUE TITLE
Videojs dash support

### ISSUE THREAD

**Issue by Anil-matcha** [Novage/p2p-media-loader#145]
Currently I see that videojs support is present for hls via hls.js. But in our case we need to support dash in videojs. Anyway you can suggest the integration to happen ? 

I happen to see some videojs-shaka github integrations like below 
https://github.com/MetaCDN/videojs-shaka-player
https://github.com/halibegic/videojs-shaka

Can we build a layer on top of these to make videojs work with shaka media player for dash

**Comment by mrlika** [comment]
Interesting projects. I think that it is possible.

**Comment by vadootvpeer** [comment]
I have made a basic integration work with https://github.com/halibegic/videojs-shaka . If it is ok I can raise a pull request.

**Comment by Anil-matcha** [comment]
I have made a basic integration work with https://github.com/halibegic/videojs-shaka. If it is ok I can try raising a pull request.

**Comment by Bruce-Hopkins** [comment]
I think I can implement this. Can I be assigned the issue?
