### ISSUE TITLE
shaka player v3 is not supported

### ISSUE THREAD

**Issue by nodegin** [Novage/p2p-media-loader#147]
TypeError: Cannot read property 'timeMs' of undefined
    at networking_engine.js:440
    at Ob (abortable_operation.js:222)
    at abortable_operation.js:183

**Comment by hkchenhongyi** [comment]
I also encountered the same problem!

**Comment by hkchenhongyi** [comment]
https://github.com/google/shaka-player/issues/2630
version change!
