### ISSUE TITLE
How do I use debug?

### ISSUE THREAD

**Issue by supersh86** [Novage/p2p-media-loader#150]
I often see debug information in the source, how to use it?

**Comment by jhemmmm** [comment]
Pretty simple.:
https://github.com/Novage/p2p-media-loader/blob/master/FAQ.md#how-to-see-that-p2p-is-actually-working

There's still more but you have to check it by yourself.

**Comment by mrlika** [comment]
Added FAQ section how to enable debug info:

https://github.com/Novage/p2p-media-loader/blob/master/FAQ.md#how-to-debug

**Comment by supersh86** [comment]
Thank you Andrey! With the help of it, I realized that safari does not support stun servers!

**Comment by mrlika** [comment]
Hmm, STUN is part of WebRTC and Safari supports it

iOS Safari doesn't support MSE API that is why downloaded over P2P video can't be played there.
On macOS and iPadOS Safari P2P video should work.
