### ISSUE TITLE
Hotlink and SegmentsStorage

### ISSUE THREAD

**Issue by shell1986** [Novage/p2p-media-loader#152]
Hello everyone, I have hotlink protection in my player, when the user contacts the manifest, it generates a key that gives access to files.
If you start downloading a file via p2p from SegmentsStorage and then interrupt the process, after a while the link becomes outdated. After the download is resumed, the HybridLoader continues to contact the server using the old links, which is why it gets denied access to the files.
It would be nice to make a condition under which the resumption of downloads updated AssetsStorage, and new files were downloaded from new links.

Всем привет, у меня в плеере стоит защита от хотлинка, при обращении пользователя манифест генерирует ключ который дает доступ к файлам.
Если начать качать файл через p2p с SegmentsStorage а потом прервать процесс, через некоторое время ссылка устаревает. После возобновления скачивания HybridLoader продолжает обращаться к серверу по старым ссылкам, на что получает отказ к доступу к файлам.
Хорошо бы сделать условие при котором возобновление скачивания обновляла AssetsStorage, а новые файлы скачивались по новым ссылкам.

**Comment by mrlika** [comment]
If master manifest URL is changed you should restart everything with the new URL

**Comment by supersh86** [comment]
and segmentdata?

**Comment by supersh86** [comment]
In the xhr settings, I added an onerror event and added a function to delete assets.
After removing assets, new ones are added, but hls does not play those files that are already loaded. Do you have an idea how to solve this problem?

**Comment by supersh86** [comment]
In the end I found a link conflict at this.onSegmentLoaded
this.segmentRequest.segmentUrl === segment.url
How important is this condition, what errors can there be if I delete it?

**Comment by mrlika** [comment]
This condition is important. It means that if we downloaded a segment and it is currently requested segment by an engine - we should answer with success status.

Does `hls.js` without P2P Media Loaders work in this use case?
