### ISSUE TITLE
p2p only work on same network ?

### ISSUE THREAD

**Issue by mindjek07** [Novage/p2p-media-loader#153]
is p2p only work on same network ?
Open demo page from my mobile desktop and laptop it's work fine on same wifi but when i switch from wifi to mobile data it's not work. (also try with windows server Location Germany )

I am newbie in p2p so don't have much idea.

**Comment by mrlika** [comment]
No. It works using WebRTC technology provided by browsers that can connect over Internet.

But if 2 browsers are behind NATs (configured not perfectly) then it is possible that they can't connect.
