### ISSUE TITLE
support videojs-http-streaming

### ISSUE THREAD

**Issue by Luxury-666** [Novage/p2p-media-loader#154]
Hi, can you add videojs-http-streaming plugin
[https://github.com/videojs/http-streaming](https://github.com/videojs/http-streaming)

latest version:

[https://cdn.jsdelivr.net/npm/@videojs/http-streaming@1.13.3/dist/videojs-http-streaming.cjs.min.js](cdn.jsdelivr.net)

```
<video-js id=vid1 width=600 height=300 class="vjs-default-skin" controls>
  <source
     src="https://example.com/index.m3u8" type="application/x-mpegURL">
</video-js>
<script src="video.js"></script>
<script src="videojs-http-streaming.min.js"></script>
<script>
var player = videojs('vid1');
player.play();
</script>
```

**Comment by mrlika** [comment]
`videojs-http-streaming` is yet another implementation of an engine to play segmented videos.

We are not planning to do an integration with this engine. The overall quality of it is much less than `hls.js` or `Shaka Engine`.
