### ISSUE TITLE
Technical documentation

### ISSUE THREAD

**Issue by marcofbb** [Novage/p2p-media-loader#155]
Hello,
If they could create a technical documentation, for example what does each file and each function, where it is injected in the codes of the players, ect. it would be of great help to be able to contribute

I really want to help! Especially to implement it in new versions of Jwplayer

Regards

**Comment by mrlika** [comment]
There is no perfect documentation currently.

But the best documentation for an open-source project is the source code.

You can check existing integration with players and hls.js engine Shaka Player

**Comment by mrlika** [comment]
Contributions are welcome!

**Comment by pedro0606** [comment]
> Hello,
> If they could create a technical documentation, for example what does each file and each function, where it is injected in the codes of the players, ect. it would be of great help to be able to contribute
> 
> I really want to help! Especially to implement it in new versions of Jwplayer
> 
> Regards

may i help you, ping me
