### ISSUE TITLE
Not an issue but need help for starting the demo

### ISSUE THREAD

**Issue by TomaIvanovTomov** [Novage/p2p-media-loader#156]
Hello, I don't  really know how to start some demo. For example:
https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-hlsjs/demo/jwplayer.html
I am cloning the repo, running `npm install` in the p2p-media-loader-hlsjs directory. But how should I proceed further to run the demo file ? Thank you and excuse me for my lack of knowledge.

**Comment by Niharika098** [comment]
@TomaIvanovTomov You can just open the html file in any browser and it should work ideally.

**Comment by pedro0606** [comment]
> Hello, I don't really know how to start some demo. For example:
> https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-hlsjs/demo/jwplayer.html
> I am cloning the repo, running `npm install` in the p2p-media-loader-hlsjs directory. But how should I proceed further to run the demo file ? Thank you and excuse me for my lack of knowledge.

ping me, i will help you demo

**Comment by mrlika** [comment]
`cd p2p-media-loader-hlsjs`
`npm i`
`npm run build`
then open jwplayer.html in a web browser

**Comment by mullerivan** [comment]
Hi there take a look at https://swarm.video/#/home is a nice production platform

cheers
