### ISSUE TITLE
Live Stream to 10,000 people

### ISSUE THREAD

**Issue by john916zhang** [Novage/p2p-media-loader#157]
Thanks for this wonderful library. Suppose I am going to have a live stream to 10,000 people. Is it possible to do it with this library? What are the hardware requirements for the source HTTP servers and TURN servers? Any information would be appreciated.

**Comment by mrlika** [comment]
Hi, yes it is possible.

TURN servers aren't applicable to this solution because it fallbacks to CDN if P2P doesn't work for a peer.

You require to install a personal Web Torrent Tracker like wt-tracker, configure P2P script with your video and do live streaming using a CDN.

P2P should offload traffic from CDN.

**Comment by john916zhang** [comment]
Thanks. Did you hold a big live stream before with this library? How was the performance? If I turn each small video segment into a webtorrent seed, will that approach have the same performance or better than this library?

**Comment by pedro0606** [comment]
> Thanks. Did you hold a big live stream before with this library? How was the performance? If I turn each small video segment into a webtorrent seed, will that approach have the same performance or better than this library?

ping me if  you need solution

**Comment by john916zhang** [comment]
@pedro0606 Yes, I do need a solution. How to ping you?

**Comment by pedro0606** [comment]
> @pedro0606 Yes, I do need a solution. How to ping you?
give me your email ?

**Comment by john916zhang** [comment]
anderson916 at gmail

**Comment by mullerivan** [comment]
Hi there take a look at https://swarm.video/#/home is a nice production platform

cheers

**Comment by mullerivan** [comment]
ping me at  telegram
https://t.me/swarmvideo

**Comment by pedro0606** [comment]
> @pedro0606 Hi, I do need a solution also. How to ping you?

my email peer9pro@gmail.com
