### ISSUE TITLE
Can improve support flowplayer hlsjs-lite pluglin?

### ISSUE THREAD

**Issue by amtbnagios** [Novage/p2p-media-loader#16]
This project is great, I like it very much! Thanks very much!

I use Flowplayer to play videos, but Flowplayer hlsjs plugin is deprecated and discontinued.
Flowplayer 7 help says: Your should use the hlsjs-lite plugin available in Flowplayer Core now.
Please see:
https://flowplayer.com/help/developers/flowplayer-7/setup#hlsjs-lite

I tested p2p-media-loader-hlsjs with flowplayer hlsjs-lite plugin,  but play the video was easy to get stuck, can you improve this ?

Thanks very much!

**Comment by mrlika** [comment]
Fixed in version 0.2.1

**Comment by mrlika** [comment]
It is already released.

The [demo](http://novage.com.ua/p2p-media-loader/demo.html) already uses built-in hlsjs-lite playback for Flowplayer

**Comment by amtbnagios** [comment]
Great! Thank you very much, I will test it!
Thanks mrlika!

**Comment by mrlika** [comment]
A quick test shows that it works. We tested only basic hls.js parameters.

**Comment by amtbnagios** [comment]
Thank you, your help is very appreciated :)
Built-in hlsjs-lite playback for Flowplayer is work perfect!
