### ISSUE TITLE
it doesn't seem to connect to my wt-tracker server.

### ISSUE THREAD

**Issue by kkwangeun** [Novage/p2p-media-loader#163]
I installed wt-tracker on my server.
./bin/wt-tracker config.json
listening xx.xx.xx.xxx:8000

And the config setting of index.html of hle-demo is as follows.

const config = {
                 segments: {
                     swarmId: this.swarmId
                 },
                 loader: {

                    trackerAnnounce:[
                      "ws://xx.xx.xx.xxx:8000" //my tracker ip
                    ]
                  }
                 }
             };

But it doesn't seem to connect to my wt-tracker server.
I can't download p2p and I can't see other peers

**Comment by amtbnagios** [comment]
wt-tracker statistics under /stats.json URL,  you can check(maybe other ssl port)
https://xx.xx.xx.xxx:8000/stats.json

**Comment by kkwangeun** [comment]
Thank you~
Setting it to SSL solved it ~
