### ISSUE TITLE
Loading P2P problem in Production

### ISSUE THREAD

**Issue by hthieu1110** [Novage/p2p-media-loader#164]
Hi,

My business had a hard time by using this plugin. I don't want to say here that it's bad, otherwise I would like to thank your team who has made a wonderful product. I just have a few questions:
- I configured our private tracker using wt-track
- I used public STUN servers (including those from Google)
- Configure and test everything to ensure that traffic would be transmitted over the P2P CDN
- Our infrastructure supports more than 10,000 viewers
 
In testing with friends who live in the same city, everything worked fine. And even with a larger group (200) in the same town, everything was fine. So ... we decided to use it on the production 3,500 viewers who are spread across the country and ... we got at least 2,000 feedback that the stream was terrible:
- lag, wait too long, hang every 15s
- sometimes in the log I see that the user was trying to load a very old chunk (the last chunk was 300 and suddenly he is loading chunk 250)

So my questions are: 
- How does this plugin handle its peers ? 
- Does it connect peers only when the peers have a good connection ? or does it put all connections to tracker ?
- If the tracker is able to track the connection quality, so I think it's between the tracker and peer, not between peers so maybe it's not efficient ?
- Do you have any suggestions to use it in production and ensure the quality of stream ? I really love this product and I'd like to use it in production.

Thanks so you helps
Yo.

**Comment by pedro0606** [comment]
hi friend,
ping me if you need solution.
contact me via email peer9pro@gmail.com

**Comment by mullerivan** [comment]
Hi there take a look at https://swarm.video/#/home is a nice production platform 

cheers

**Comment by wvalko** [comment]
> Hi,
> 
> My business had a hard time by using this plugin. I don't want to say here that it's bad, otherwise I would like to thank your team who has made a wonderful product. I just have a few questions:
> 
> * I configured our private tracker using wt-track
> * I used public STUN servers (including those from Google)
> * Configure and test everything to ensure that traffic would be transmitted over the P2P CDN
> * Our infrastructure supports more than 10,000 viewers
> 
> In testing with friends who live in the same city, everything worked fine. And even with a larger group (200) in the same town, everything was fine. So ... we decided to use it on the production 3,500 viewers who are spread across the country and ... we got at least 2,000 feedback that the stream was terrible:
> 
> * lag, wait too long, hang every 15s
> * sometimes in the log I see that the user was trying to load a very old song (the last song was 300 and suddenly he is loading song 250)
> 
> So my questions are:
> 
> * How does this plugin handle its peers ?
> * Does it connect peers only when the peers have a good connection ? or does it put all connections to tracker ?
> * If the tracker is able to track the connection quality, so I think it's between the tracker and peer, not between peers so maybe it's not efficient ?
> * Do you have any suggestions to use it in production and ensure the quality of stream ? I really love this product and I'd like to use it in production.
> 
> Thanks so you helps
> Yo.

Did you ever find any resolve here?  We're facing similar issues once taking to a larger scope.

**Comment by pedro0606** [comment]
> > Hi,
> > My business had a hard time by using this plugin. I don't want to say here that it's bad, otherwise I would like to thank your team who has made a wonderful product. I just have a few questions:
> > 
> > * I configured our private tracker using wt-track
> > * I used public STUN servers (including those from Google)
> > * Configure and test everything to ensure that traffic would be transmitted over the P2P CDN
> > * Our infrastructure supports more than 10,000 viewers
> > 
> > In testing with friends who live in the same city, everything worked fine. And even with a larger group (200) in the same town, everything was fine. So ... we decided to use it on the production 3,500 viewers who are spread across the country and ... we got at least 2,000 feedback that the stream was terrible:
> > 
> > * lag, wait too long, hang every 15s
> > * sometimes in the log I see that the user was trying to load a very old song (the last song was 300 and suddenly he is loading song 250)
> > 
> > So my questions are:
> > 
> > * How does this plugin handle its peers ?
> > * Does it connect peers only when the peers have a good connection ? or does it put all connections to tracker ?
> > * If the tracker is able to track the connection quality, so I think it's between the tracker and peer, not between peers so maybe it's not efficient ?
> > * Do you have any suggestions to use it in production and ensure the quality of stream ? I really love this product and I'd like to use it in production.
> > 
> > Thanks so you helps
> > Yo.
> 
> Did you ever find any resolve here? We're facing similar issues once taking to a larger scope.

hi wvaloko,
Plz chat with me via email peer9pro@gmail.com.
i will discuss with you.

**Comment by hthieu1110** [comment]
> > Hi,
> > My business had a hard time by using this plugin. I don't want to say here that it's bad, otherwise I would like to thank your team who has made a wonderful product. I just have a few questions:
> > 
> > * I configured our private tracker using wt-track
> > * I used public STUN servers (including those from Google)
> > * Configure and test everything to ensure that traffic would be transmitted over the P2P CDN
> > * Our infrastructure supports more than 10,000 viewers
> > 
> > In testing with friends who live in the same city, everything worked fine. And even with a larger group (200) in the same town, everything was fine. So ... we decided to use it on the production 3,500 viewers who are spread across the country and ... we got at least 2,000 feedback that the stream was terrible:
> > 
> > * lag, wait too long, hang every 15s
> > * sometimes in the log I see that the user was trying to load a very old song (the last song was 300 and suddenly he is loading song 250)
> > 
> > So my questions are:
> > 
> > * How does this plugin handle its peers ?
> > * Does it connect peers only when the peers have a good connection ? or does it put all connections to tracker ?
> > * If the tracker is able to track the connection quality, so I think it's between the tracker and peer, not between peers so maybe it's not efficient ?
> > * Do you have any suggestions to use it in production and ensure the quality of stream ? I really love this product and I'd like to use it in production.
> > 
> > Thanks so you helps
> > Yo.
> 
> Did you ever find any resolve here? We're facing similar issues once taking to a larger scope.

Unfortunately not yet :( we have to suspend this feature for now.

@pedro0606  If you have any idea which can help, I'd really love to learn from you. Thanks.

**Comment by wvalko** [comment]
> Unfortunately not yet :( we have to suspend this feature for now.
> 
> @pedro0606 If you have any idea which can help, I'd really love to learn from you. Thanks.

Thanks for the reply! I'm guessing this project is dead as you posted 3 months ago, and seems like there was 0 response from project owner :(  

@pedro0606 , I have sent you an email. 

If anyone reading has any suggestions to OP issues, please share!  We've spent 6 months, with this piece being a core part of our solution, and running into this road block now is... disappointing!

**Comment by mullerivan** [comment]
@wvalko feel free to try https://swarm.video  we make it work with over 500k concurrent users  
info@swarm.video

**Comment by hoangvietfreelancer** [comment]
> * Do you have any suggestions to use it in production and ensure the quality of stream ? I really love this product and I'd like to use it in production.

@hthieu1110 My suggestion is that you should add the user's town/city to [swarmId](https://github.com/Novage/p2p-media-loader/blob/master/FAQ.md#how-to-manually-set-swarm-id) to make them only peer with each other in the same town/city.

**Comment by mullerivan** [comment]
@hoangvietfreelancer 
We have those  features on swarm.video :) feel free to test it

**Comment by hthieu1110** [comment]
> > * Do you have any suggestions to use it in production and ensure the quality of stream ? I really love this product and I'd like to use it in production.
> 
> @hthieu1110 My suggestion is that you should add the user's town/city to [swarmId](https://github.com/Novage/p2p-media-loader/blob/master/FAQ.md#how-to-manually-set-swarm-id) to make them only peer with each other in the same town/city.

Thanks for your suggestion, I've used it already but it did not help :( I think that we should investigate more on all parametters of p2p-media-loader to have a good config

**Comment by jhemmmm** [comment]
> > > * Do you have any suggestions to use it in production and ensure the quality of stream ? I really love this product and I'd like to use it in production.
> > 
> > 
> > @hthieu1110 My suggestion is that you should add the user's town/city to [swarmId](https://github.com/Novage/p2p-media-loader/blob/master/FAQ.md#how-to-manually-set-swarm-id) to make them only peer with each other in the same town/city.
> 
> Thanks for your suggestion, I've used it already but it did not help :( I think that I should investigate more on all parametters of p2p-media-loader to have a good config

What I did on p2p-media-loader was to copy my default player configuration, I used to have these kind of problems but I was able to fix it.

```
requiredSegmentsPriority: 8,
simultaneousP2PDownloads: 20,
simultaneousHttpDownloads: 1, //this is the important part, where i can only request 1 http request at a time, this would help both client and my streaming server save bandwidth a lot.
```

**Comment by anesuc** [comment]
> > > > * Do you have any suggestions to use it in production and ensure the quality of stream ? I really love this product and I'd like to use it in production.
> > > 
> > > 
> > > @hthieu1110 My suggestion is that you should add the user's town/city to [swarmId](https://github.com/Novage/p2p-media-loader/blob/master/FAQ.md#how-to-manually-set-swarm-id) to make them only peer with each other in the same town/city.
> > 
> > 
> > Thanks for your suggestion, I've used it already but it did not help :( I think that I should investigate more on all parametters of p2p-media-loader to have a good config
> 
> What I did on p2p-media-loader was to copy my default player configuration, I used to have these kind of problems but I was able to fix it.
> 
> ```
> requiredSegmentsPriority: 8,
> simultaneousP2PDownloads: 20,
> simultaneousHttpDownloads: 1, //this is the important part, where i can only request 1 http request at a time, this would help both client and my streaming server save bandwidth a lot.
> ```

Anyone here that has tried this solution on a large scale?

**Comment by thaidh1907** [comment]
> Anyone here that has tried this solution on a large scale?
i was used.
Contact me via email peer9pro@gmail.com.
i will discuss with you.

**Comment by anesuc** [comment]
> > Anyone here that has tried this solution on a large scale?
> > i was used.
> > Contact me via email [peer9pro@gmail.com](mailto:peer9pro@gmail.com).
> > i will discuss with you.

I don't really have money to put into a paid product atm which I assume this is related to.

**Comment by mullerivan** [comment]
> > > Anyone here that has tried this solution on a large scale?
> > > i was used.
> > > Contact me via email [peer9pro@gmail.com](mailto:peer9pro@gmail.com).
> > > i will discuss with you.
> 
> I don't really have money to put into a paid product atm which I assume this is related to.

@anesuc we have a free way to use our system :)

**Comment by snowinszu** [comment]
cdnbye can solve these issues with affordable price: https://www.cdnbye.com/en/views/web/introduction.html
