### ISSUE TITLE
Hls.js/clappr Stopped working,  also basic usage example

### ISSUE THREAD

**Issue by gvalo** [Novage/p2p-media-loader#17]
So, viewing the demo example on the novage site runs as expected, however when i take the clappr example from [here](https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-hlsjs#p2p-media-loader---hlsjs-integration): 

No p2p action happens. it gets this far, and then nothing more. No attempts on a websocket connection or any relevant debug logs:
`p2pml:hybrid-loader loader settings +0ms Object
p2p-media-loader-core.min.js:25 p2pml:p2p-media-manager peer ID +0ms 629918747b9e2edd7c1b36e713174b339446c714`

Its a bit of an odd one, i previously had this working in a much more complicated setup and then today it stopped functioning, even in this simplified example.

The same is happening in both FF and Chrome latest on mac and windows, for me at least.

Is anyone able to reproduce this bug?

**Comment by mrlika** [comment]
You are right. It is broken for latest Clappr 0.3.x. Please use Clappr 0.2.93:

change
https://cdn.jsdelivr.net/npm/clappr@latest

to
https://cdn.jsdelivr.net/npm/clappr@0.2.93

**Comment by gvalo** [comment]
Ok, so it seems i was hitting two problems. The initial one that threw me off, i think is related to manifest url & segment format. It results in exactly the same symptom. The stream plays fine but no further p2p action after that log entry.

I have a multi bitrate stream, with the master playlist and variants in different subfolders. Example:
https://a.com/b/identifier/master.m3u8
https://a.com/c/different-identifier/variant.m3u8
https://a.com/c/different-identifier/xxxx.ts

I have tried overriding the swarmId but it doesn't help. Any way this might cause a problem? The URLs can end up quite long too.

**Comment by defrinex** [comment]
I have the same problem with Clappr 0.2.93. Debug shows only these lines. Player loads and video starts without any problem. But tracker is not loading and no p2p activity.

![image](https://user-images.githubusercontent.com/9140369/48672852-24aa9100-eb4c-11e8-92aa-c502b8521805.png)

**Comment by mrlika** [comment]
Clappr issue fixed in dd121abfaba7ad5f2eb1395e8d8b1b42ad5635d7
Playlist and variants in different subfolders issue fixed in 94f637d7fe8b96ab8afb9075c2bb32fc182a62d9
