### ISSUE TITLE
httpDownloadMaxPriority and p2pDownloadMaxPriority interactions

### ISSUE THREAD

**Issue by MasterEvilAce** [Novage/p2p-media-loader#173]
Let's say forwardSegmentCount = 30.

How do these two values interact with the above, and why do they exist? (What scenarios are they useful for?)
httpDownloadMaxPriority
p2pDownloadMaxPriority

If I set them both to a LOWER number than 30, is it correct that we will never have 30 forward segments read to go? It seems to me that p2pDownloadMaxPriority should always basically be = to the forwardSegmentCount, otherwise you're limiting the entire point of p2p sharing? What is the benefit of a higher forwardSegmentCount than p2pDownloadMaxPriority?

Let's say we wanted to reduce the reliance on http downloads. If we set httpDownloadMaxPriority to 15, then we have a smaller buffer that can expand if there are peers connected, up to 30. This makes sense in an environment where everyone could be at a different point in the playlist.

However, in an environment where all players are relatively sync'd (within 5 seconds of another) this would not be useful, though, right? Because nobody would have segments past 16-30 to share via p2p. So really in this scenario, httpDownloadMaxPriority, p2pDownloadMaxPriority and forwardSegmentCount should all be set to the same number.... or is this not correct?

The environment I have set up is a VOD playlist (all fragments are accounted for from the get-go), but all players are in-sync with each other, ideally about 1 second apart.) I am utilizing p2p-media-loader to reduce the strain on the server, and allow everyone to also buffer ahead about 5 minutes of content. It works pretty well I am just looking to tweak. With about 4 users connected, it seems there's about a 50%/50% p2p to http ratio.

I also notice that the player does not buffer beyond requiredSegmentsPriority EVER, until p2p-media-loader manages to connect to the tracker, which I find perhaps a little strange... it would make a little sense to download up to the httpDownloadMaxPriority, and when connected all those pieces become instantly share-able. Is this a bug or is there a way to enable this ability?
It seems like the tracker connection speed is completely based on the announce interval, so there's quite a delay before the p2p aspect comes into play.

**Comment by mrcolak** [comment]
> I also notice that the player does not buffer beyond requiredSegmentsPriority EVER, until p2p-media-loader manages to connect to the tracker, which I find perhaps a little strange...

This is really important. When there is no peer, player does not buffer beyond requiredSegmentsPriority.

Lets say requiredSegmentsPriority set to 3 and httpDownloadMaxPriority set to 200
In this case only 3 segments will be download instead of 200 if there is no peer available.

This bug makes videos to keep buffer when there is no peer available. Because not enough segments downloads. @mrlika
