### ISSUE TITLE
Bad folders structure

### ISSUE THREAD

**Issue by piranna** [Novage/p2p-media-loader#186]
`main` entry in `package.json` files is pointing to `dist` folder, that usually is being used to store the browser bundles, while in this case the browser bundles are in `build`, that usually is a temporal folder. Project is using Typescript files, so they should be in `src` folder, being in `lib` the transpiled ones.

So: lib -> src, dist -> lib, build -> dist

**Comment by mrlika** [comment]
Thanks for the clarification. We will review folder structure changes and apply them to the next major release.

**Comment by piranna** [comment]
welcome
