### ISSUE TITLE
H265 in webview

### ISSUE THREAD

**Issue by vipeweb** [Novage/p2p-media-loader#196]
Hello, I would like to know if there is any way to run h265 on the webview android?

I implemented p2p-media but more than 80% of my audience comes from android, but much of my content is done in h265 in which, as I understand it, Webview does not support it, I would have to implement it in exoplayer or something native, I would have something to do to support the h265?

**Comment by hoangvietfreelancer** [comment]
Could you describe more about it?
Because as far as I know, Android support [H265](https://developer.android.com/guide/topics/media/media-formats#video-codecs)

**Comment by vipeweb** [comment]
I tried to run videos on h265 within a webview but it doesn't seem to work, even though my device is supported

I heard that the Android webview does not support the h265

**Comment by hoangvietfreelancer** [comment]
Can you play it on normal browser?
Also, has you test webview with h264 and what stream type are you using? Dash or HLS?
