### ISSUE TITLE
UDP Torrent tracker

### ISSUE THREAD

**Issue by mullerivan** [Novage/p2p-media-loader#20]
Hi there  Nice  project. Im tring to  use it  with a different  tracker , but  managed to make it  work just with bittorrent-tracker, there is a way to  Use it with UDP or to change it  to  Another  tracker  on WSS..

short history im tring to use a  tracker  to oprtimize

**Comment by mrlika** [comment]
The project is hardcoded to use WebTorrent trackers over WSS. No ability to replace tracker library without changes to the code.

UDP is not possible if you run it in a browser.

WebTorrent tracker protocol is open and you can create your own compatible tracker:

https://github.com/yciabaud/webtorrent/blob/beps/bep_webrtc.rst

**Comment by mullerivan** [comment]
Thanks  for  the  fast answer, 
 one  more  question about  using a different  WSS  tracker   instet of  bittorrent-tracker
