### ISSUE TITLE
VideoJs 7 support HLS with VHS

### ISSUE THREAD

**Issue by Vladislavik** [Novage/p2p-media-loader#216]
Hi, please can you add support VideoJs 7 with builtin HLS support via VHS

**Comment by Phillipip** [comment]
+1

**Comment by snowinszu** [comment]
Hi, cdnbye supports HLS with VHS, see https://github.com/swarm-cloud/hls-sw-p2p-engine/blob/main/demo/videojs-vhs.html

**Comment by Vladislavik** [comment]
I should pay cdnbuy for my users traffic? It is so stupid.

Ср, 23 февр. 2022 г. в 13:41, snowinszu ***@***.***>:

**Comment by ckcr4lyf** [comment]
> Hi, cdnbye supports HLS with VHS, see https://github.com/swarm-cloud/hls-sw-p2p-engine/blob/main/demo/videojs-vhs.html

Please do not advertise on open source projects. I have reported you btw.
