### ISSUE TITLE
Increasing The Peer Ratio

### ISSUE THREAD

**Issue by defrinex** [Novage/p2p-media-loader#22]
Hello,

How can we increase peer ratio? Any specific way like more tracker server or changing some config etc.

For me currently only %20 of my streams goes over peer traffic. Other %80 still loading from servers. When I was using peer5 this ratio was around %40-%50.

Thanks to you I have my own peer network now 🥇  💯 👍 

But I wanted to know if its possible to improve performance or not.

Thanks :)

**Comment by mrlika** [comment]
20% of peer traffic is not what we estimated. This is definitely can be improved. Can you do more investigation and provide details why peers are not sharing the video.

I am guessing that for some reason very often a peer cannot connect with peer candidates given by the tracker.

How many peers in average a peer gets from tracker in yours network?

Also, I think we have to extend the following events to provide peer ID:

```TypeScript
// current
loader.on(Events.PieceBytesDownloaded, function (method, bytes) {})
loader.on(Events.PieceBytesUploaded, function (method, bytes) {})

// change to this
loader.on(Events.PieceBytesDownloaded, function (method, bytes, peerId) {})
loader.on(Events.PieceBytesUploaded, function (method, bytes, peerId) {})
```
Extending events will allow to track with how many peers P2P exchange is actually performed.

**Comment by defrinex** [comment]
Hello,

I think I have found a solution. My p2p engine settings was set to defaults. Yesterday I change some values and got peer ratio up to %36. (the ratio I'm talking about is daily overall)

```
cachedSegmentExpiration: 1000*60*60,
cachedSegmentsCount: 500,
simultaneousP2PDownloads: 10,
bufferedSegmentsCount: 20,
p2pSegmentDownloadTimeout: 5000
```

Now I have another question about **cachedSegmentExpiration** and **cachedSegmentsCount**

**cachedSegmentsCount**
The default value of this setting is 30 but on our system videos have overall 1500 segments so 30 is probably a very low value. Is it dangerous to set this value something like 1000-1500?

Are these caches writing to users _memory or disk_? I mean Is there any limits for these settings? Like you can't set cachedSegmentExpiration more than 1 hour or cachedSegmentsCount up to max 200 etc.

**Comment by mrlika** [comment]
You are talking about VOD streams. Those 2 settings should be configured depending on video size and your goal.

The segments for P2P sharing are stored in the memory of the browser and it is probably the biggest issue. But if your videos are rather small you can configure the values to store all the segments in the memory.

You can put cachedSegmentExpiration to a big value. By default, it is configured for 5 minutes. A peer will delete older segments from the memory and stop their P2P sharing.

cachedSegmentsCount is another setting that limits the number of segments in the memory for P2P sharing. You can increase it too to any reasonable value.

**Comment by mrlika** [comment]
The default configuration is good for live P2P ready streams. P2P Media Loader has to be tuned for video on demand streams.

**Comment by defrinex** [comment]
Lets say I set cachedSegmentsCount to 1500 and cachedSegmentExpiration to 1:30 hours.

What will happend if one of the peer got out of memory and cant store 1500 segments. Will peer's computer freeezes or browser crash? 

Or just dropping old segments when can't place new one?

**Comment by mrlika** [comment]
```JS
var target = []; while (true) target.push(new Uint8Array(1024 * 1024));
```
When I run this in Ubuntu Chromium console it sometimes crashes, sometimes hang, sometimes says "Aw, Snap! Something went wrong while displaying this web page.", sometimes throws the exception:
```
Uncaught RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at <anonymous>:1:43
```
In most cases few things described above happen simultaneously :-)

**Comment by mrlika** [comment]
By the way, there is a property for this in Chrome:

```
> window.performance.memory.jsHeapSizeLimit
< 2217857988
```

**Comment by Er-rchydy** [comment]
Live streams and  VOD streams are pretty different, it would be good if there is a section in the documentation that explain the proper settings to get  the most from this library. 
there are many factors that will increase the P2P ratio for every situation, for example  Live stream where the segments are 15s or even 20s when the latency is not an issue,   compared to Live stream with 5s segments. the P2P ratio in the first case may be twice or even more of the second case. but if we use the same configs in both situations we will get the same P2P ratio. the same thing goes for VOD streams.
so it will be really helpful to add a section in the docs talking about this scenarios and how to choose the best settings to get the most of this library.

**Comment by mrlika** [comment]
VOD configuration is described in FAQ now: https://github.com/Novage/p2p-media-loader/blob/master/FAQ.md
