### ISSUE TITLE
Peer Segment Download Timeout

### ISSUE THREAD

**Issue by defrinex** [Novage/p2p-media-loader#23]
Hello,

I see that sometimes peers can't upload in high speeds.

In this case if reciever encounter this type of peer It starts to wait until the downloading segment from slow connection peer complete. But when player reaches that segment, Its just freezes and waiting the segment download finish. 

So my question is;

1. p2pSegmentDownloadTimeout represents downloading timeout or connection timeout?
2. If Its connection timeout, Is there any way to set downloading timeout?

I've try to set p2pSegmentDownloadTimeout to 5000 but It didn't solve the issue.

**Comment by mrlika** [comment]
> p2pSegmentDownloadTimeout represents downloading timeout or connection timeout?

It is the connection timeout (i.e. timeout for the response from the remote peer that it is willing to send us the requested segment) and not the timeout of segment data download.

Documentation should be improved.

**Comment by defrinex** [comment]
I've write some code snipped to handle this downloading timeout situation. This 5 second interval is checking active downloading segments every time and if the downloaded byte value is not change for the next tick, it will cancel that segment download process.

```
var peerSegmentStats = [];
window.setInterval(function() {
	engine.loader.p2pManager.peers.forEach(function(peer) {
		if(peer.downloadingSegment !== null) {
			if(peerSegmentStats[peer.downloadingSegment.id] !== peer.downloadingSegment.bytesDownloaded)
				peerSegmentStats[peer.downloadingSegment.id] = peer.downloadingSegment.bytesDownloaded;
			else {
				console.log("cancelling", peer.downloadingSegment.id ,"request from", peer.id, (peer.downloadingSegment.bytesDownloaded/1024).toFixed(2), "/", (peer.downloadingSegment.size/1024).toFixed(2));
				delete peerSegmentStats[peer.downloadingSegment.id];
				engine.loader.p2pManager.peerSegmentRequests.delete(peer.downloadingSegment.id);
				peer.cancelSegmentRequest();
			}
	    }
	});
}, 1000*5)

engine.loader.on(p2pml.core.Events.SegmentLoaded, function (segment) {
    delete peerSegmentStats[segment.id];
});
```

**Comment by defrinex** [comment]
> Currently, if a remote peer is slow and failed to deliver full segment in time, the P2P download will be aborted and HTTP download initiated.

What do you mean by **in time** Is there an option to set this time?

What I need is something like this;

> If a remote peer is slow and failed to deliver full segment in 5 seconds, the P2P download will be aborted and HTTP download initiated. And It's configuring like this;
> peerFailAbortTime: 5000

In my case, all segments should be downloaded at least 5 seconds. I already make this happend with the code send you above but If there is a way to do this within the library, I would like to use that for integrity.

**Comment by mrlika** [comment]
By default with "requiredSegmentsPriority = 1" **in time** means that the segment you are downloading should not become of priority 0 or 1.

Priority 0 has the segment that goes next after currently playing one. Priority 1 has the segment next after segment with priority 0.

**Comment by defrinex** [comment]
I still didn't understand how am I going to limit the segment download time within X seconds. :(

**Comment by mrlika** [comment]
It is not possible. And I am not sure that it should be implemented.

> But when player reaches that segment, Its just freezes and waiting the segment download finish.

Checking this now. It should not happen.

**Comment by mrlika** [comment]
You can try to increase requiredSegmentsPriority or segment duration. Probably not enough time to download slow P2P segments over HTTP.

**Comment by defrinex** [comment]
> ```
> var peerSegmentStats = [];
> window.setInterval(function() {
> 	engine.loader.p2pManager.peers.forEach(function(peer) {
> 		if(peer.downloadingSegment !== null) {
> 			if(peerSegmentStats[peer.downloadingSegment.id] !== peer.downloadingSegment.bytesDownloaded)
> 				peerSegmentStats[peer.downloadingSegment.id] = peer.downloadingSegment.bytesDownloaded;
> 			else {
> 				console.log("cancelling", peer.downloadingSegment.id ,"request from", peer.id, (peer.downloadingSegment.bytesDownloaded/1024).toFixed(2), "/", (peer.downloadingSegment.size/1024).toFixed(2));
> 				delete peerSegmentStats[peer.downloadingSegment.id];
> 				engine.loader.p2pManager.peerSegmentRequests.delete(peer.downloadingSegment.id);
> 				peer.cancelSegmentRequest();
> 			}
> 	    }
> 	});
> }, 1000*5)
> 
> engine.loader.on(p2pml.core.Events.SegmentLoaded, function (segment) {
>     delete peerSegmentStats[segment.id];
> });
> ```

This is working fine so we can close this case.

**Comment by defrinex** [comment]
```
var engine = new p2pml.hlsjs.Engine({
  loader: {
    cachedSegmentExpiration: 1000 * 60 * 60 * 2,
    cachedSegmentsCount: 800,
    simultaneousP2PDownloads: 15,
    bufferedSegmentsCount: 30,
    p2pSegmentDownloadTimeout: 5000
  }
});
```

With this configuration, I've managed to increase peer ratio from ~%20 to ~%50... There were no reports from users for now. So I'll try to increase these numbers a little bit if noone complain about crashes or etc.
