### ISSUE TITLE
Can not get peer in public network

### ISSUE THREAD

**Issue by ducnmhn** [Novage/p2p-media-loader#230]
In the past, everything was great. But a week ago, I checked it can not get peer in public network. I tested on my product, public demo (http://novage.com.ua/p2p-media-loader/demo.html) and same problem. If I open new tab, I can see new peer with name "Unknown" but If I open in new computer with other network , other public IP, it can not connect each other..

Anyone have same my issuse ?

**Comment by Be4t5** [comment]
Same issue here

**Comment by ckcr4lyf** [comment]
It could be your ISP has a CGNAT, or stricter firewalls that disalllow UPnP (e.g. University Networks). In such a situation, even if you use something like BitTorrent the two won't be able to connect to each other.

You can try adding a TURN server (if I'm not mistaken) which will act as a relay, but that does mean all bandwidth will flow through that

**Comment by ducnmhn** [comment]
I'm checked it, when I change my network everything ok. So I think something wrong with firewall of my internet or my router
