### ISSUE TITLE
Add more HTTP peers

### ISSUE THREAD

**Issue by anesuc** [Novage/p2p-media-loader#246]
Hi all,

I was wondering if there is a way to have more than 1 "source"/CDN to improve performance from HTTP peers alone? I am using clappr with shaka.

Thanks

**Comment by Vladislavik** [comment]
You can add two servers with same content on it with and one
domain/subdomain via same “A” record.

Сб, 9 апр. 2022 г. в 20:56, Anesu Chiodze ***@***.***>:
