### ISSUE TITLE
First 2 segments always by http, can it be changed?

### ISSUE THREAD

**Issue by thenikin** [Novage/p2p-media-loader#25]
Is there any way to force the download over p2p of every segment including the first 2 that by default are downloader over http?

thanks

**Comment by mrlika** [comment]
P2P Media Loader implements P2P assisted video delivery approach. It means that the source stream is located on a CDN or a Media Server and accessible over HTTP.

For example, if you have 5 peers in the P2P swarm then at least one peer have to download the segments from source and redistribute them over P2P to other 4 peers. Maximum possible overall P2P ratio, in this case, is 80%.

For 10 peers maximum possible overall P2P ratio is 90%. For 100 peers 99%. For 1000 peers in the best case (that is practically not possible) is 99.9%.

Assuming above overall 100% P2P is not achievable with this approach and you can not achieve "force the download over p2p of every segment" for all the peers.

While designing, implementing and testing P2P algorithms of the library we came to decision that the first few segments have to be downloaded over HTTP. It provides best user experience - fast playback on startup with no difference compared to standard HTTP download.

P2P requires more time to initialize, find peers and do P2P download than raw HTTP download. Moreover, if you start download first segments over P2P from a slow peer or even broken peer your playback will stall and your site visitors will be disappointed.

"force the download over p2p of every segment" has another drawback - if a peer can't connect to other peers over P2P (for example behind NAT not configured well for P2P) then playback will never start.

You can configure to try event first 2 segments to download over P2P by using [requiredSegmentsPriority](https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-core/README.md#loader--new-hybridloadersettings) property like:

```JS
const config = {
    loader: {
        requiredSegmentsPriority: -1
    }
};

const engine = new p2pml.hlsjs.Engine(config);
```
But it will not give you 100% P2P ratio and may lead to stalls and not reliable playback.

**Comment by thenikin** [comment]
thanks
