### ISSUE TITLE
P2P for JW Player not compatible with iOS?

### ISSUE THREAD

**Issue by hijuuijj** [Novage/p2p-media-loader#254]
With Clappr I never had problems on iOS (using P2P) but with JW Player it doesn't load the video.

Is there any solution?

**Comment by renatofrota** [comment]
> Is there any solution?

Yes. Keep using Clappr. 💡 

Joke aside, why are you trying to substitute the software you never had a problem to something else? 🙄

**Comment by hijuuijj** [comment]
> > Is there any solution?
> 
> Yes. Keep using Clappr. 💡
> 
> Joke aside, why are you trying to substitute the software you never had a problem to something else? 🙄

Because Clappr does not support multiple audio tracks and JW Player seems to be a bit faster changing bitrate.

**Comment by umpol69** [comment]
p2p-media-loader don't support iOS Safari on iPhone.
