### ISSUE TITLE
Could get myself's peer info( id and remoteAddress)?

### ISSUE THREAD

**Issue by amtbnagios** [Novage/p2p-media-loader#26]
Hi, Could you tell me :
How to  get myself's peer info( id and remoteAddress) or just peer.id? 
Thanks!

**Comment by mrlika** [comment]
Getting peerId and other peer details are missing. A gap in the API. I think it will add it in next release.

**Comment by amtbnagios** [comment]
Thank you very much!

**Comment by greenya** [comment]
Implemented getDetails() in 27df0532ebbba0329a3b217afdd5da861f0ecffb.

Basically now after engine has been created you can get self peer Id like:
`engineInstance.getDetails().loader.peerId`

**Comment by mrlika** [comment]
I think getting the local IP address is kind of a hack and can be easily done if required without P2P Media Loader: https://stackoverflow.com/questions/32837471/how-to-get-local-internal-ip-with-javascript

**Comment by amtbnagios** [comment]
@greenya @mrlika  Thanks you a lot!
