### ISSUE TITLE
Updating "videojs-hlsjs-plugin" breaks p2p-media-loader.

### ISSUE THREAD

**Issue by VideoFX** [Novage/p2p-media-loader#260]
The "videojs-hlsjs-plugin" by streamroot (https://github.com/streamroot/videojs-hlsjs-plugin) uses an old version of hls.js (v0.13.2). However, if you compile the plugin with newer versions of hls.js, the video will play, but it breaks p2p-media-loader.

Is there any way to upgrade p2p-media-loader, and/or videojs-hlsjs-plugin, to work with newer versions of HLS?

More background:
The reason we use "videojs-hlsjs-plugin" with "p2p-media-loader" is so that we can use video.js as the player.

**Comment by fujinxiang** [comment]
see PR, try to build yourself 

https://github.com/Novage/p2p-media-loader/pull/261

https://github.com/Novage/p2p-media-loader/pull/203

**Comment by rozenrod** [comment]
@fujinxiang Can you please tell me how to compile the release into regular js?

**Comment by rozenrod** [comment]
Oops, figured it out...) Should have just run the commands: `npm run browserify`, `npm run minify`
