### ISSUE TITLE
Newer versions of HLS.js (newer than the one used in the demo) won't work with p2p

### ISSUE THREAD

**Issue by anesuc** [Novage/p2p-media-loader#263]
Hi all,

I have been trying to play an HLS playlist which has issues playing in the demo. However, it turns out it was some issue related to that version of HLS. Updating it fixes the issue. However, with p2p enabled (tested using the plyr player) it won't play. If I set the p2p enabled variable to false it works fine. A bit more info on this from this issue: https://github.com/Novage/p2p-media-loader/issues/262

Thanks

**Comment by DavidRadan** [comment]
I have a feeling that this library abanded by its founders , shame really it could be a amazing library !

**Comment by radiantmediaplayer** [comment]
Do we know about any open-source alternative?

**Comment by DavidRadan** [comment]
Not that i know of !
I have a feeling that it's a simple interfacing problem such as ( custom hls loader ) that doesn't work with newest version of hls.js .
10x

**Comment by radiantmediaplayer** [comment]
There is a v1 hls.js PR that seem to work: https://github.com/Novage/p2p-media-loader/pull/203. It just it would be better if it was merged/reviewed. Also there is the same issue with latest Shaka player versions.
