### ISSUE TITLE
Function download Range not working

### ISSUE THREAD

**Issue by truonghoainhanit** [Novage/p2p-media-loader#27]
Hi All,

I want download range but it not woking with me

request.setRequestHeader("Range", segment.range); 

segment.range is undefined 

my file .m3u8 and server support download range

#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:11
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:8.217089,
#EXT-X-BYTERANGE:212440@0
5bd9fd91ce7e1b08435acb87-000.ts
#EXTINF:10.427778,
#EXT-X-BYTERANGE:2814360@212440
5bd9fd91ce7e1b08435acb87-000.ts
#EXTINF:2.794644,
#EXT-X-BYTERANGE:128592@3026800
5bd9fd91ce7e1b08435acb87-000.ts
..........

![image](https://user-images.githubusercontent.com/19868417/50391641-ff77f680-0779-11e9-9e78-2da0d3432492.png)

**Comment by mrlika** [comment]
It is not about failover or partial segments downloads.

It is about [Byte-Range Support for Segments in HLS](https://developer.apple.com/library/archive/technotes/tn2288/_index.html#//apple_ref/doc/uid/DTS40012238-CH1-BYTE_RANGE_SUPPORT_FOR_SEGMENTS) - i.e. when a file contains more than one or all segments (fMP4 for example).
