### ISSUE TITLE
How do I add my wt-tracker to p2p-media-loader?

### ISSUE THREAD

**Issue by v-7-3** [Novage/p2p-media-loader#275]
How do I add my wt-tracker to p2p-media-loader?

**Comment by Awqre** [comment]
`		const config = {
			loader: {
				trackerAnnounce: [
					"wss://tracker.tracker.com",
				],
			}
		}
		if (p2pml.hlsjs.Engine.isSupported()) {
			var engine = new p2pml.hlsjs.Engine(config);
`
