### ISSUE TITLE
Not working in the latest version of Chrome

### ISSUE THREAD

**Issue by anesuc** [Novage/p2p-media-loader#277]
I have been using this library for a project of mine. Today I noticed the P2P isn't detecting new peers. Even if you open it in a new tab. It seems it still works on my other computer and I have not updated Chrome on it. Any ideas what changes in Chrome have resulted in this breaking?

**Comment by anesuc** [comment]
I have been doing my own debugging looking through the code and such. The issue is related to this update: https://groups.google.com/g/discuss-webrtc/c/L0qDWipd7VE?pli=1

The fix is to remove query options in the STUN URL in p2p-media-loader-core.js .  I can't find the corresponding code in this repo though from a quick look.

In other words: `stun:global.stun.twilio.com:3478?transport=udp` becomes  `stun:global.stun.twilio.com:3478`

**Comment by renatofrota** [comment]
Thank you for providing more info and the fix. It did work for me as well.

**Comment by anesuc** [comment]
> Thank you for providing more info and the fix. It did work for me as well.

Yeah I have had my fair share of going to a thread where they say "all god figured it out" or never come back. So I make my best effort to come back haha

**Comment by mvpavx** [comment]
Your are my real life super hero bro!
Thank you.  It help me saving cost so much.
