### ISSUE TITLE
WebSocket connection to 'wss://tracker.novage.com.ua/' failed: 

### ISSUE THREAD

**Issue by NewSingleHostReverseProxy** [Novage/p2p-media-loader#283]
Hello,
When running player gets the error: WebSocket connection to 'wss://tracker.novage.com.ua/' failed: 
I have tried your demo http://novage.com.ua/p2p-media-loader/demo.html but it doesn't show that p2p is working. How to check if it's actually working? Or I am using it wrong?

`<script>
        const config = {
            loader: {
                trackerAnnounce: [
                    "wss://tracker.tracker.co",
                ],
            }
        }
        if (p2pml.hlsjs.Engine.isSupported()) {
            var engine = new p2pml.hlsjs.Engine();

            var player = new Clappr.Player({
                parentId: "#player",
                source: "https://xxx.org:8088/hls/index.m3u8",
                mute: true,
                autoPlay: true,
                height: 500,
                width: '100%',
                playback: {
                    hlsjsConfig: {
                        liveSyncDurationCount: 7,
                        loader: engine.createLoaderClass()
                    }
                }
            });

            p2pml.hlsjs.initClapprPlayer(player);
        } else {
            document.write("Not supported :(");
        }
    </script>`

**Comment by snowinszu** [comment]
Here is the available trackers:
https://github.com/snowinszu/wt-tracker/blob/master/README.md
