### ISSUE TITLE
How to hide source of media file?

### ISSUE THREAD

**Issue by okgame** [Novage/p2p-media-loader#30]
Like streamroot and cdnbye, when peer load data from p2p, in F12 - network tab, client not see media source of HTTP.
![image](https://user-images.githubusercontent.com/22207363/50735185-26ecab80-11dd-11e9-9e35-61cc023c7203.png)

**Comment by Yokutto** [comment]
The segments is not showing on Chrome Console because it's downloading by a P2P Websocket.
If you see the "Frames" tab on the websocket request you will see the segments being downloaded.

**Comment by okgame** [comment]
What diffrent of novage p2p and cdnbye/streamroot?
Can novage p2p support this feature?

**Comment by mrlika** [comment]
It is not hiding sources. It is not possible to hide HTTP requests from developer tools.

What you see is that peer 1 downloads all the segments from HTTP and peer 2 downloads all the segments from P2P.

Close peer 1 and peer 2 will start to download all from HTTP and you will see the HTTP sources on peer 2.
