### ISSUE TITLE
Peers wont connect !! 

### ISSUE THREAD

**Issue by marxc88** [Novage/p2p-media-loader#304]
Please can anyone help , peers just wont connect!!
anyone with the same error? can help me

**Comment by TheNexter** [comment]
Demo is not working i can confirm, the wss tracker is not running, look console

![image](https://github.com/Novage/p2p-media-loader/assets/17613028/785f7054-5403-4582-a023-cdddec367052)

**Comment by snowinszu** [comment]
Here is the available trackers:
https://github.com/snowinszu/wt-tracker/blob/master/README.md

**Comment by stevenking888** [comment]
> Here is the available trackers: https://github.com/snowinszu/wt-tracker/blob/master/README.md

You tracker can not build with error with mocha ReDoS vulnerability

minimatch  <3.0.5
Severity: high
minimatch ReDoS vulnerability - https://github.com/advisories/GHSA-f8q6-p94x-37v3
fix available via `npm audit fix --force`
Will install mocha@10.2.0, which is a breaking change
node_modules/mocha/node_modules/minimatch

request  *
Severity: moderate
Server-Side Request Forgery in Request - https://github.com/advisories/GHSA-p8p7-x288-28g6
Depends on vulnerable versions of tough-cookie
No fix available
node_modules/request
  coveralls  *
  Depends on vulnerable versions of request
  node_modules/coveralls

tough-cookie  <4.1.3
Severity: moderate
tough-cookie Prototype Pollution vulnerability - https://github.com/advisories/GHSA-72xf-g2v4-qvf3
No fix available
node_modules/tough-cookie

8 vulnerabilities (4 moderate, 1 high, 3 critical)

**Comment by snowinszu** [comment]
You can use the service directly:
wss://us-tracker1.peerhub.net
wss://ca-tracker1.peerhub.net
wss://uk-tracker1.peerhub.net
wss://ge-tracker1.peerhub.net

**Comment by marxc88** [comment]
thanks i put that and works now
