### ISSUE TITLE
Not Working P2P

### ISSUE THREAD

**Issue by bleachhun** [Novage/p2p-media-loader#317]
Hy,

Public tracker or Private “bittorent” tracker not working

public Only connect wss and only http get testing 3 user all http download not peer.

bittorent tracker (own): invalid info_hash 

clappr player

if (p2pml.hlsjs.Engine.isSupported()) {
		
		const config = {
  segments:{
	      swarmId: lejatszas, // any unique string

    // number of segments to pass for processing to P2P algorithm
    forwardSegmentCount:50, // usually should be equal or greater than p2pDownloadMaxPriority and httpDownloadMaxPriority
  },
  loader:{
	     trackerAnnounce: [
      "wss://ge-tracker1.peerhub.net/announce","wss://ge-tracker1.peerhub.net","wss://wss.soulmovie.hu"
    ],
    // how long to store the downloaded segments for P2P sharing
    cachedSegmentExpiration:86400000,
    // count of the downloaded segments to store for P2P sharing
    cachedSegmentsCount:1000,

    // first 4 segments (priorities 0, 1, 2 and 3) are required buffer for stable playback
    requiredSegmentsPriority:3,

    // each 1 second each of 10 segments ahead of playhead position gets 6% probability for random HTTP download
    httpDownloadMaxPriority:9,
    httpDownloadProbability:0.06,
    httpDownloadProbabilityInterval: 1000,
  }
};

                     var engine = new p2pml.hlsjs.Engine(config);

         var player = new Clappr.Player({
            source: lejatszas,
            playback: {
                playInline: !0,
                hlsjsConfig: {
                    liveSyncDurationCount: 7, // To have at least 7 segments in queue
                    loader: engine.createLoaderClass(),
                },
            },
            parentId: "#player-container",
            width: "100%",
            height: "100%"
        });

        p2pml.hlsjs.initClapprPlayer(player);

   
    } else { }

please help!

**Comment by bleachhun** [comment]
Update: wt-tracker create connect and not connect peer….. dead this project?

**Comment by snowinszu** [comment]
Here is the available trackers:
https://github.com/snowinszu/wt-tracker/blob/master/README.md
