### ISSUE TITLE
host in mau domain pleass anser

### ISSUE THREAD

**Issue by v-7-3** [Novage/p2p-media-loader#319]
If I copy the codes and put them on my domain, will they work without problems?

<script src="https://cdn.jsdelivr.net/npm/p2p-media-loader-hlsjs@0.6.2/build/p2p-media-loader-hlsjs.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/p2p-media-loader-core@0.6.2/build/p2p-media-loader-core.min.js"></script>
for example
<script src="https://my.domain.com/p2p-media-loader-hlsjs.min.js"></script>

<script src="https://my.domain.com/p2p-media-loader-core.min.js"></script>

**Comment by mrlika** [comment]
Yes you can host the files on your domain
