### ISSUE TITLE
V1 Can't start

### ISSUE THREAD

**Issue by Neptunespace** [Novage/p2p-media-loader#328]
I am not a JS develloper, i just want to report this error

```
  VITE v5.0.12  ready in 213 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://XXXXXXXXXXXX:5173/
  ➜  Network: http://XXXXXXXXXXXX:5173/
  ➜  press h + enter to show help
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:5173/' ]
}

Node.js v21.6.2
 ELIFECYCLE  Command failed with exit code 1.
```

How i start the app :
docker run -it --rm --network=host node bash
git clone --branch v1 https://github.com/Novage/p2p-media-loader
cd p2p-media-loader
pnpm i
cd demo
pnpm i
pnpm run dev

**Comment by mrlika** [comment]
It is your docker configuration, most likely. Works for me just fine via GitHub Codespaces.

```bash
pnpm i
pnpm dev
```

![image](https://github.com/Novage/p2p-media-loader/assets/1469266/57b0f5a9-9466-4fd3-96e0-b64c900358c5)

<img width="377" alt="image" src="https://github.com/Novage/p2p-media-loader/assets/1469266/bb7d3085-666e-4b61-9769-090498762a5f">

**Comment by Neptunespace** [comment]
Thx men, i solve the problem with your help ;)

For anyone who want to run in docker container (node image) :
git clone --branch v1 https://github.com/Novage/p2p-media-loader
cd p2p-media-loader
apt update && apt install xdg-utils -y
pnpm i
pnpm dev
