### ISSUE TITLE
Fallback to

### ISSUE THREAD

**Issue by defrinex** [Novage/p2p-media-loader#35]
Hello,

Is it possible to make a fallback to normal palyer when p2p is not possible?

On IE or Edge, It just gives error and video is not playable.

**Comment by mrlika** [comment]
Fallback is implemented in the demo: http://novage.com.ua/p2p-media-loader/demo.html. The demo works in IE and iOS Safari but without P2P.

For browsers support please refer to [Web browsers support](https://github.com/Novage/p2p-media-loader#web-browsers-support) table.

IE is not supported at all starting from version 0.3. Problem is that we do not use transpiller but popular npm modules (like debug 4.x) are switching to ES6 syntax. It means that produced .js files can not be parsed by IE.

Do not load the library on IE otherwice it will give you error in console.

Edge doesn't support WebRTC Data Channels API (i.e. actually P2P). iOS Safari does not support Media Source Extensions API. To detect not supported browsers you have to check:

``` JS
Hls.isSupported() or shaka.Player.isBrowserSupported() - check MSE support 
p2pml.core.HybridLoader.isSupported() - check P2P support
```

If not supported do not initialize P2P Media Loader at all.

**Comment by mrlika** [comment]
I just fixed fallback in the demo. You can check the code.
