### ISSUE TITLE
Multiple CDNs for identical stream

### ISSUE THREAD

**Issue by ctlaltdefeat** [Novage/p2p-media-loader#36]
I currently have my broadcast on multiple servers, and do a simple client-side random to decide what source to use in that client's player.
Would it be possible to have the same peer network for all CDNs? Does this happen automatically based on the hash of the files? If not, is there some way to have control over this?

Thanks in advance.

**Comment by mrlika** [comment]
Yes, it is possible. For the same stream that can be accessed by multiple URL you have to specify the same [swarmId](https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-hlsjs#engine--new-enginesettings) configuration parameter.
By default swarmId is eqal to the stream URL without query parameters so for streams by different URLs the segments are not share over P2P.

**Comment by Chocobozzz** [comment]
As a side question, would it be possible to have multiple CDN for the same stream? For example, download segment1 from CDN1, segment2 from CDN2 and if it does not work try with CDN1 etc?

**Comment by mrlika** [comment]
I think it is possible to implement. Currently P2P Media Loader uses only single manifest and segment URLs.

For example Shaka Player supports providing multiple URIs for download: https://shaka-player-demo.appspot.com/docs/api/shakaExtern.html#.Request

But looks like hls.js doesn't support this: https://github.com/video-dev/hls.js/blob/master/docs/API.md#loader

**Comment by ctlaltdefeat** [comment]
For some reason I'm unable to get this to work. I set a custom swarmId, and only clients that are using the same CDN are able to share data. Here is a rough snippet of what I have:

```
var engine = new p2pml.hlsjs.Engine({'segments': {'swarmId': 'broadcast_id'}});
engine.loader.on(p2pml.core.Events.PieceBytesUploaded, function (method, bytes) {console.log(`Uploaded ${bytes} bytes to peers`)})
switch (Math.floor((Math.random() * 2) + 1)) {
    case 1:
        var source = `cdn1`
        break;
    default:
        var source = `cdn2`
        break;
}
var player = new Clappr.Player({source: source, parentId: 'id', playback: {hlsjsConfig: {loader: engine.createLoaderClass()}}});
p2pml.hlsjs.initClapprPlayer(player);
```

If I start two clients and they happen to have the same CDN, then I can see in the console lag that they share data, otherwise they do not. Anything I'm missing here?

**Comment by mrlika** [comment]
Your code should work. Most likely the streams are not the same somehow. For example they can have different #EXT-X-MEDIA-SEQUENCE that is used to identify the same segments: 
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:1693717
#EXTINF:4.0,
media_w125104900_b5556000_1693717.ts
#EXTINF:4.0,
media_w125104900_b5556000_1693718.ts
#EXTINF:4.0,
media_w125104900_b5556000_1693719.ts
#EXTINF:4.0,
media_w125104900_b5556000_1693720.ts
#EXTINF:4.0,
media_w125104900_b5556000_1693721.ts
#EXTINF:4.0,
media_w125104900_b5556000_1693722.ts
#EXTINF:4.0,
media_w125104900_b5556000_1693723.ts
```

If you can share the streams or at least manifest .m3u8 files

**Comment by ctlaltdefeat** [comment]
The stream is rsynced across the servers, and the manifest looks something like this:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:11880
#EXTINF:3.336000,
#EXT-X-PROGRAM-DATE-TIME:2019-01-17T18:26:27.543+0100
stream-1547745982.ts
#EXTINF:1.669000,
#EXT-X-PROGRAM-DATE-TIME:2019-01-17T18:26:30.879+0100
stream-1547745986.ts
#EXTINF:1.668000,
#EXT-X-PROGRAM-DATE-TIME:2019-01-17T18:26:32.548+0100
stream-1547745987.ts
```

If  you have an email or something I can privately send you the web links for the streams.

**Comment by mrlika** [comment]
You can send URLs privately to mrlika@gmail.com then I can investigate

**Comment by mrlika** [comment]
Thanks, I found the bug - swarmId is not applied when a stream has no master playlist. It will be fixed shortly and included into new release.

The workaround is to use a master playlist for your stream.

**Comment by dage66788** [comment]
Provide a signaling server address built by individuals, and purchase the right to use it for one year, wss://tracker.dplayer.club/
