### ISSUE TITLE
demo is only http, none p2p

### ISSUE THREAD

**Issue by nvtienlg** [Novage/p2p-media-loader#383]
https://novage.com.ua/p2p-media-loader/demo.html

I tried to open many tabs/browsers but only see http traffic, can you please check the demo page to see what is wrong?

Many thanks for great codes

**Comment by mrlika** [comment]
Hi, we develop and work on the demo every day. P2P works.

You can check console errors. Also, you can enable additional logging in the debug interface of the demo: https://novage.com.ua/p2p-media-loader/demo?debug=true

**Comment by nvtienlg** [comment]
Hello,

I do not see any errors in console. I tested on latest macOS (chrome, firefox, safari) and only http
It works on android phone. I will test on more devices then let you know
