### ISSUE TITLE
`p2pml` not found after upgrading to v1.0.1

### ISSUE THREAD

**Issue by wrfly** [Novage/p2p-media-loader#384]
I upgraded the lib to v1.0.1 recently but got error `p2pml is not defined`

![image](https://github.com/Novage/p2p-media-loader/assets/7827389/8a0e07dc-85e7-47ec-bfdf-fee15ec6d99c)

**Comment by mrlika** [comment]
Hi @wrfly,

P2P Media Loader v1 features a new API. Please check the docs on how to use it: https://novage.github.io/p2p-media-loader/docs/latest

**Comment by wrfly** [comment]
Hi @mrlika ,

Thanks for your reply, I've checked the documents, and the `<script type="module">` works fine.

But I'm facing issue with `webpack`. In the older versons, I just use:

```
import { Engine, initHlsJsPlayer } from 'p2p-media-loader-hlsjs';
```

but now when I import with

```
import { HlsJsP2PEngine } from 'p2p-media-loader-hlsjs';
```

the console reports error `HlsJsP2PEngine not defined`

**Comment by mrlika** [comment]
Thanks for reporting. We will test with Webpack on Monday. Do you specify more details what frameworks are you using.

Please check in our repository: we have a React demo. It uses Vite. And we import it into our Astro website without any issues.

**Comment by wrfly** [comment]
Thank you master!

**Comment by wrfly** [comment]
Hi master @mrlika , the CI failed https://github.com/Novage/p2p-media-loader/actions/runs/9746617636/job/26898569591 and the npm haven't been updated. Could you help to retry? thanks!
