### ISSUE TITLE
Module "events" has been externalized for browser compatibility. Cannot access "events.EventEmitter" in client code

### ISSUE THREAD

**Issue by nvtienlg** [Novage/p2p-media-loader#385]
Hello,

I created a vanilla js project using Vite, import this lib will result in mentioned error
`npm create vite@latest
...
npm install p2p-media-loader-hlsjs hls.js`

in main.js
`import Hls from 'hls.js';
import { HlsJsP2PEngine } from 'p2p-media-loader-hlsjs';`

<img width="902" alt="Screenshot 2024-07-01 at 12 24 02" src="https://github.com/Novage/p2p-media-loader/assets/105366918/9b34fcfa-ed6b-4575-af3f-1ca687da77e0">
<img width="904" alt="Screenshot 2024-07-01 at 12 22 25" src="https://github.com/Novage/p2p-media-loader/assets/105366918/e8030651-190e-4ba3-b7d0-19bb8be6265c">

If i try using importmap method then everything is fine. But since importmap is not fully supported by all browsers, so i prefer to use npm method. Can you check this?

**Comment by mrlika** [comment]
Hi @nvtienlg, I think node polyfills required by `bittorrent-tracker` package are missing. Check our Vite config for reference: https://github.com/Novage/p2p-media-loader/blob/main/demo/vite.config.ts
