### ISSUE TITLE
wrong url of segments if m3u8 was redirected

### ISSUE THREAD

**Issue by Vladislavik** [Novage/p2p-media-loader#40]
hi, if m3u8 src is 

> server.com/redirector.php?video.m3u8

and it redirect to

> storage.com/hash/video.m3u8

script download m3u8 successfuly, after that try download ts files from server.com, but should from storage.com/hash/

**Comment by mrlika** [comment]
Fixed. You can build from the sources and test. It will be included into next v0.4 release.
