### ISSUE TITLE
Highload

### ISSUE THREAD

**Issue by Vladislavik** [Novage/p2p-media-loader#42]
Yesterday i was try your script, after i was send to each webtorrent server (wss://tracker.openwebtorrent.com, wss://tracker.btorrent.xyz and wss://tracker.fastcast.nz) 5k viewers, they go down. How many messages script send to each server, that they cant do this work and go down... 
Who store how many segments have peer - Server or peer ask another peers does they have segments?
Do you have goLang programmer?

**Comment by mrlika** [comment]
Trackers are only to exchange signaling information and form swarms. Information about segments is shared directly between peers.

Do not use public webtorrent trackers to test high load scenarios because you will not get reliable results. Run your own instances. The trackers are free and open source:

* https://github.com/webtorrent/bittorrent-tracker
* https://github.com/DiegoRBaquero/uWebTorrentTracker

**Comment by mrlika** [comment]
Let us know about your test results. We are interested in making the solution more reliable.

**Comment by mrlika** [comment]
I think it should be able to do the work. I do not see what features of GoLang can help. Concurrency is not used in the trackers.

If there is a bottleneck in the trackers and if it can not be resolved by JavaScript implementation we can initiate GoLang tracker development.

Please read about the trackers performance in theirs issues and documentation sections:
https://github.com/webtorrent/bittorrent-tracker/issues/88

**Comment by Vladislavik** [comment]
I have write you to contact@novage.com.ua can you answer.

**Comment by mrlika** [comment]
https://github.com/webtorrent/bittorrent-tracker/issues/308

> I recently lowered my limits to about 5k after moving to a smaller server. FastCast and OpenWebtTorrent should handle 5k - 50k, depends on the servers and if other processes are consuming memory.
> 
> I wouldn't rely on public trackers for a large operations. For example, large websites (1k+ concurrent users) are blocked from using BTorrent tracker unless sponsoring.

**Comment by mullerivan** [comment]
@Vladislavik  I'm working in a tracker  that can handle your traffic  and we can give you a test   shut me an email 
mulleivan@gmail.com
