### ISSUE TITLE
Weak stream hash function

### ISSUE THREAD

**Issue by alopatindev** [Novage/p2p-media-loader#427]
Thanks for making this awesome software.

I wonder why [MD5 with a truncated byte](https://github.com/Novage/p2p-media-loader/blob/fe59c09e8226687f0478836becdaf2bbb39c10ba/packages/p2p-media-loader-core/src/utils/peer.ts#L12) was chosen as a stream hash?

Is there any technical limitation that prevents from using more collision-resistant algorithms?

Thanks.

**Comment by mrlika** [comment]
The limitation is that BitTorrent and WebTorrent `peerId` is only 20 bytes: https://github.com/webtorrent/bittorrent-peerid

**Comment by mrlika** [comment]
Hi, the limitation is that `info hash` is 20 bytes, and we failed to find a good, small, supported library for SHA-1 hash without dependencies. In case of issues, we can change to SHA-1 with a major version update.
