### ISSUE TITLE
hls.js 0.14.17 compatible

### ISSUE THREAD

**Issue by hkchenhongyi** [Novage/p2p-media-loader#433]
dplayer
hls.js 0.14.17

Seek stops loading when the area is not loaded

Call seek again to restore to normal (less than 10 seconds)

This problem only occurs with lower versions of hls.js

hls.js 1+ is normal

p2p-media-loader version 2.0.1

**Comment by DimaDemchenko** [comment]
We prioritize working with up-to-date technologies, supporting only HLS v1 and above. Supporting deprecated versions is unnecessary, especially since older HLS versions are incompatible with iOS. Please use up-to-date HLS versions to ensure optimal performance, compatibility, and security.

Regards

**Comment by hkchenhongyi** [comment]
> We prioritize working with up-to-date technologies, supporting only HLS v1+. Supporting deprecated versions is unnecessary, especially since older HLS versions are incompatible with iOS. Please use up-to-date HLS versions to ensure optimal performance, compatibility, and security.
> 
> Regards

ok!i got it!

There is another problem onPeerClose is triggered repeatedly
It will be triggered twice when disconnecting

**Comment by hkchenhongyi** [comment]
> > > 我们优先使用最新技术，仅支持 HLS v1+。无需支持弃用版本，尤其是因为旧版 HLS 与 iOS 不兼容。请使用最新版 HLS 以确保最佳性能、兼容性和安全性。
> > > 问候
> > 
> > 
> > 好的！我明白了！
> > 还有一个问题 onPeerClose 被重复触发 断开连接时会触发两次
> 
> 这是预期的行为，因为我们订阅了与连接相关的多个事件，每个事件都可能触发 onPeerConnectionClosed。
> 
> ```
> connection.on("close", this.onPeerConnectionClosed);
> connection.on("end", this.onPeerConnectionClosed);
> connection.on("finish", this.onPeerConnectionClosed);
> ```
> 
> 当连接关闭时，每个事件都可以独立调用 onPeerConnectionClosed 处理程序，从而产生多个触发器。

Do I need to maintain a peerlist myself?
Used to count the number of peers.

**Comment by DimaDemchenko** [comment]
> > > > 我们优先使用最新技术，仅支持 HLS v1+。无需支持弃用版本，尤其是因为旧版 HLS 与 iOS 不兼容。请使用最新版 HLS 以确保最佳性能、兼容性和安全性。
> > > > 问候
> > > 
> > > 
> > > 好的！我明白了！
> > > 还有一个问题 onPeerClose 被重复触发 断开连接时会触发两次
> > 
> > 
> > 这是预期的行为，因为我们订阅了与连接相关的多个事件，每个事件都可能触发 onPeerConnectionClosed。
> > ```
> > connection.on("close", this.onPeerConnectionClosed);
> > connection.on("end", this.onPeerConnectionClosed);
> > connection.on("finish", this.onPeerConnectionClosed);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 当连接关闭时，每个事件都可以独立调用 onPeerConnectionClosed 处理程序，从而产生多个触发器。
> 
> Do I need to maintain a peerlist myself? Used to count the number of peers.

If you need to track peer count accurately, it's better to maintain a peer list by peerId. Use onPeerConnect to add peers and onPeerClose to remove them by peerId. This prevents counting multiple disconnections for the same peer if onPeerClose is triggered more than once.

**Comment by hkchenhongyi** [comment]
> > > > > 我们优先使用最新技术，仅支持 HLS v1+。无需支持弃用版本，尤其是因为旧版 HLS 与 iOS 不兼容。请使用最新版 HLS 以确保最佳性能、兼容性和安全性。
> > > > > 问候
> > > > 
> > > > 
> > > > 好的！我明白了！
> > > > 还有一个问题 onPeerClose 被重复触发 断开连接时会触发两次
> > > 
> > > 
> > > 这是预期的行为，因为我们订阅了与连接相关的多个事件，每个事件都可能触发 onPeerConnectionClosed。
> > > ```
> > > connection.on("close", this.onPeerConnectionClosed);
> > > connection.on("end", this.onPeerConnectionClosed);
> > > connection.on("finish", this.onPeerConnectionClosed);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 当连接关闭时，每个事件都可以独立调用 onPeerConnectionClosed 处理程序，从而产生多个触发器。
> > 
> > 
> > Do I need to maintain a peerlist myself? Used to count the number of peers.
> 
> If you need to track peer count accurately, it's better to maintain a peer list by peerId. Use onPeerConnect to add peers and onPeerClose to remove them by peerId. This prevents counting multiple disconnections for the same peer if onPeerClose is triggered more than once.

ok!i got it!
thank you very much!
