### ISSUE TITLE
Loading resource problem

### ISSUE THREAD

**Issue by hkchenhongyi** [Novage/p2p-media-loader#434]
When connected to a peer, the http resource will be loaded infinitely!
Until all resources are loaded, this puts a heavy burden on the http server.

When using shaka to play DRM, P2P fails and resources are loaded repeatedly!

**Comment by hkchenhongyi** [comment]
```
let core = {
		swarmId: swarmId,							
		isP2PDisabled: false,							
		simultaneousHttpDownloads: 1,			
		simultaneousP2PDownloads: 10,			
		httpErrorRetries: 5,					
		p2pErrorRetries: 5,						
		cashedSegmentsCount: 1024,		
		cachedSegmentsCount: 10,			
		highDemandTimeWindow: 30, 		
		httpDownloadTimeWindow: 3000,	
		p2pDownloadTimeWindow: 6000, 		
		p2pNotReceivingBytesTimeoutMs: 10e3,	
		p2pInactiveLoaderDestroyTimeoutMs: 30e3, 
		httpNotReceivingBytesTimeoutMs: 3e3, 	
	};
```
this my config！

**Comment by DimaDemchenko** [comment]
> ```
> let core = {
> 		swarmId: swarmId,							
> 		isP2PDisabled: false,							
> 		simultaneousHttpDownloads: 1,			
> 		simultaneousP2PDownloads: 10,			
> 		httpErrorRetries: 5,					
> 		p2pErrorRetries: 5,						
> 		cashedSegmentsCount: 1024,		
> 		cachedSegmentsCount: 10,			
> 		highDemandTimeWindow: 30, 		
> 		httpDownloadTimeWindow: 3000,	
> 		p2pDownloadTimeWindow: 6000, 		
> 		p2pNotReceivingBytesTimeoutMs: 10e3,	
> 		p2pInactiveLoaderDestroyTimeoutMs: 30e3, 
> 		httpNotReceivingBytesTimeoutMs: 3e3, 	
> 	};
> ```
> 
> this my config！


You configured that you want to download 3000 seconds of your video in advance. This `httpDownloadTimeWindow` works only when there are more than 2 peers in a network. Without any peers we rely only on `highDemandTimeWindow`. This means that segments are downloaded in advance as intended, without causing an endless load of resources.

[Read the configuration parameters description](https://novage.github.io/p2p-media-loader/docs/v2.0/types/p2p_media_loader_core.StreamConfig.html)

Regards

**Comment by hkchenhongyi** [comment]
> The library downloads segments based on network conditions:
> 
> * No Peers: If there are no peers, only segments within the highDemandTimeWindow are downloaded.
> * With Peers: If peers are available, the library also pre-loads segments using HTTP and P2P combined, controlled by httpDownloadTimeWindow and p2pDownloadTimeWindow.
> 
> In your configuration, httpDownloadTimeWindow is set to 3000 seconds, allowing the library to download segments up to 3000 seconds ahead of the current play position. Note that segments in this time window are downloaded in random order and only if other peers don’t already have them.

Yes, but I don't want it to buffer infinitely!
There is no parameter to control it to buffer 10 segments and then stop, play a segment and then continue buffering!

**Comment by DimaDemchenko** [comment]
The library doesn’t load segments indefinitely. To limit buffering to a specific number of segments, such as 10, follow these steps:

Determine the average segment duration (in seconds) from your playlist.
Multiply this duration by the desired number of segments (e.g., 10).
Set the resulting value as the httpDownloadTimeWindow in the core config.
With this setup, the library will buffer up to 10 segments and then pause pre-loading until you start watching more segments

**Comment by hkchenhongyi** [comment]
> > ```
> > let core = {
> > 		swarmId: swarmId,							
> > 		isP2PDisabled: false,							
> > 		simultaneousHttpDownloads: 1,			
> > 		simultaneousP2PDownloads: 10,			
> > 		httpErrorRetries: 5,					
> > 		p2pErrorRetries: 5,						
> > 		cashedSegmentsCount: 1024,		
> > 		cachedSegmentsCount: 10,			
> > 		highDemandTimeWindow: 30, 		
> > 		httpDownloadTimeWindow: 3000,	
> > 		p2pDownloadTimeWindow: 6000, 		
> > 		p2pNotReceivingBytesTimeoutMs: 10e3,	
> > 		p2pInactiveLoaderDestroyTimeoutMs: 30e3, 
> > 		httpNotReceivingBytesTimeoutMs: 3e3, 	
> > 	};
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this my config！
> 
> You configured that you want to download 3000 seconds of your video in advance. This `httpDownloadTimeWindow` works only when there are more than 2 peers in a network. Without any peers we rely only on `highDemandTimeWindow`. This means that segments are downloaded in advance as intended, without causing an endless load of resources.
> 
> [Read the configuration parameters description](https://novage.github.io/p2p-media-loader/docs/v2.0/types/p2p_media_loader_core.StreamConfig.html)
> 
> Regards

sorry!is my bad!!
I misread the unit, the default 3000 I thought was milliseconds!

and thanks for your answer！
