### ISSUE TITLE
shaka-player dash can‘t use p2p

### ISSUE THREAD

**Issue by hkchenhongyi** [Novage/p2p-media-loader#435]
shaka-player dash type can‘t use p2p

I use shaka-player hls drm and it works fine with p2p
But I use it to play dash format files.
It plays fine, but it won't work with p2p?
The loader is also not using p2p-media-loader！

**Comment by mrlika** [comment]
Hi! Could you please share more details, specifically the stream that's not playing on your end? This will help us investigate and resolve the issue effectively.

**Comment by hkchenhongyi** [comment]
this dash config can't use p2p！
```
<?xml
version="1.0" encoding="UTF-8"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" xmlns:cenc="urn:mpeg:cenc:2013" minBufferTime="PT2S" type="static" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" mediaPresentationDuration="PT1204S">
    <Period>
        <AdaptationSet contentType="video" maxWidth="" maxHeight="" frameRate="25" subsegmentAlignment="true" par="40:17">
            <Representation bandwidth="11437024" codecs="avc1.640033" mimeType="video/mp4" sar="1:1">
                <BaseURL>https://XXX</BaseURL>
                <SegmentBase indexRange="1016-3939">
                    <Initialization range="0-1015"/>
                </SegmentBase>
            </Representation>
        </AdaptationSet>
        <AdaptationSet contentType="audio" subsegmentAlignment="true">
            <Role schemeIdUri="urn:mpeg:dash:role:2011"/>
            <Representation bandwidth="45899" codecs="mp4a.40.5" mimeType="audio/mp4">
                <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011"/>
                <BaseURL>https://XXX</BaseURL>
                <SegmentBase indexRange="956-3879">
                    <Initialization range="0-955"/>
                </SegmentBase>
            </Representation>
        </AdaptationSet>
    </Period>
</MPD>
```

shaka drm
url use：
data:text/plain;base64,XXX。 Can't be used p2p
https://XXX Can be used p2p

```
#EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,URI="XXX",GROUP-ID="default-audio-group",NAME="stream_0",AUTOSELECT=YES,CHANNELS="2"
#EXT-X-STREAM-INF:BANDWIDTH=4710135,CODECS="avc1.640028,mp4a.40.2",AUDIO="default-audio-group"
XXX
```

**Comment by hkchenhongyi** [comment]
shaka drm 
m3u8 URL used data:text/plain;base64,XXX can't enable p2p

shaka dash
my xml config can play! but no enable p2p!

**Comment by DimaDemchenko** [comment]
@hkchenhongyi 
What Shaka player version do you use?

**Comment by DimaDemchenko** [comment]
> > @hkchenhongyi What Shaka player version do you use?
> 
> 4.11.11
```
shakaP2PEngine.addEventListener(
          "onChunkDownloaded",
          (bytesLength, downloadSource, peerId) => {
            console.log(
              `Downloaded ${bytesLength} bytes from ${downloadSource} ${peerId ? "from peer " + peerId : "from server"}`,
            );
          },
        );
 ```
        
Could you subscribe to this event and check if there are any logs indicating a download through HTTP

**Comment by hkchenhongyi** [comment]
None of the loaders worked!
I checked the developer tools
The one that loads the segments is shaka, not the p2p loader

![QQ_1732036937050](https://github.com/user-attachments/assets/75039f57-b10e-4ed1-b1c4-0ef287067c02)

**Comment by DimaDemchenko** [comment]
Hi @hkchenhongyi,

We’ve added support for data URLs in the upcoming release, which will address the issue you’ve reported. Please stay tuned as the new version will be released soon.

Thank you for your patience and understanding!

Best regards

**Comment by hkchenhongyi** [comment]
> Hi @hkchenhongyi,
> 
> We’ve added support for data URLs in the upcoming release, which will address the issue you’ve reported. Please stay tuned as the new version will be released soon.
> 
> Thank you for your patience and understanding!
> 
> Best regards

ok! thank you very much!
