### ISSUE TITLE
how do you use dash?

### ISSUE THREAD

**Issue by jimmywarting** [Novage/p2p-media-loader#48]
is there an example how to use p2pml with dash.js?

**Comment by mrlika** [comment]
`p2p-media-loader` has no integration with `dash.js` (PRs are welcome). For MPEG-DASH support you can use integration with `Shaka Player` playback engine.

**Comment by mrlika** [comment]
See https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-shaka#p2p-media-loader---shaka-player-integration
