### ISSUE TITLE
Player loads segments out of order and stops

### ISSUE THREAD

**Issue by V7resspect** [Novage/p2p-media-loader#51]
When I run VOD HLS, the player loads the manifest segments in a different order. If the next segment is not loaded, the player stops.

This is what the Network tab in chrome displays:
..._3.ts
..._4.ts
..._20.ts
..._5.ts
..._10.ts
..._6.ts
..._7.ts
..._19.ts

At this point, the player stopped, because the 8th segment did not have time to load. Further, the player does not load any segments, the video stops playing.

This error occurs even on your demo, if you put a link to VOD HLS:
http://novage.com.ua/p2p-media-loader/demo.html?url=https%3A%2F%2Fwowza.peer5.com%2Fvod%2Fsmil%3Abbb_abr.smil%2Fplaylist.m3u8&type=jwplayer

My browser is Chrome 72.0.3626.121

**Comment by mrlika** [comment]
Should be already fixed in 71e6ea2313c714f4b3963dff7c7896c72620b4bb
You can build from the latest sources and test or wait for new release (most likely week)
