### ISSUE TITLE
Not work when WebRTC IP disabled

### ISSUE THREAD

**Issue by ewwink** [Novage/p2p-media-loader#54]
I use Chrome extension `uBlock Origin`, by default the option for `Privacy > Prevent WebRTC from leaking local IP addresses` is enabled, when this option enabled in console I see websocket is connected and no error but cannot find another peer, It is required to use WebRTC IP?

**Comment by mrlika** [comment]
Most likely you can not find peers in your local network because it makes local IPs to be not accessible to ICE.
