### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by r4de** [Novage/p2p-media-loader#57]
Hey mrlika & team,

is there an detailed instruction, how to install p2p-media-loader on an windows root/dedicated server? We want to test it in our own environment.

Keep up the good work ;)

**Comment by mrlika** [comment]
`P2P Media Loader` itself is a `JavaScript` library that doesn't require installation.

You can include it into your page directly (see [basic usage example](https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-hlsjs#basic-usage)) or bundle into your application using `NPM` packages.

By default the library is configured to use free trackers, but for high loads your need to run your personal WebTorrent tracker. You can use our [wt-tracker](https://github.com/Novage/wt-tracker). It should work on Windows.
