### ISSUE TITLE
Can you please add some download and upload to the demos ?

### ISSUE THREAD

**Issue by Er-rchydy** [Novage/p2p-media-loader#6]
Can you please add something that shows how much download and upload every peer made to the other demos ( [like this demo](https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-hlsjs/demo/clappr.html) ) without graphs, a simple div that got updated every 5 seconds for example would be helpful.
because even if you enable debugging there are lot of informations, where sometimes you want just to see the performance ( p2p download vs http download ).
thanks for the great library

**Comment by mrlika** [comment]
We already have this information in our big demo:

Git: https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-demo
Hosted: http://novage.com.ua/p2p-media-loader/demo.html

Small demos ([like this demo](https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-hlsjs/demo/clappr.html)) are intended to be as simple as possible and you are free to copy them and extend for your needs.

**Comment by Er-rchydy** [comment]
@mrlika yes i saw the big demo, but if someone want to test the performance with big number of users is not going to use the big demo, and put it in his website for like 20k users you know what i mean.
i don't know how to add it myself, can you show us what we should add in this code to console how much data has been transferred via P2P vs HTTP 
`<script>
        if (p2pml.hlsjs.Engine.isSupported()) {
            var engine = new p2pml.hlsjs.Engine();
            var player = new Clappr.Player({
                parentId: "#video",
                source: "https://akamai-axtest.akamaized.net/routes/lapd-v1-acceptance/www_c4/Manifest.m3u8",
                hlsjsConfig: {
                    liveSyncDurationCount: 7, // To have at least 7 segments in queue
                    loader: engine.createLoaderClass()
                }
            });
            p2pml.hlsjs.initClapprPlayer(player);
            player.setVolume(1); // 1%
            player.play();
            this.engine.on(p2pml.core.Events.PieceBytesDownloaded, this.onBytesDownloaded.bind(this));
            this.engine.on(p2pml.core.Events.PieceBytesUploaded, this.onBytesUploaded.bind(this));            
        } else {
            document.write("Not supported :(");
        }
    </script>`

**Comment by Er-rchydy** [comment]
ok thanks, i have one more question. 
what are the of a server specifications (bandwidth, cpu, ...) that i will need to test this library for 20k viewers with non HD video i will test it with 520p ?  ( and if you have some hosting suggestions, cheapest once because you know i'm doing this just for testing purposes )

**Comment by mrlika** [comment]
On the server side the library uses webtorrent tracker. It just exchanges peer connection information (like a torrent tracker). It doesn't deal with data that is sent between peers so video size doesn't matter:

https://github.com/webtorrent/webtorrent
or
https://github.com/DiegoRBaquero/uWebTorrentTracker

By default public webtorrent trackers are used but I think for your 20k users swarm you should run your personal webtorrent tracker and configure it with the library.
Webtorrent tracker doesn't require much CPU and bandwith.

**Comment by Er-rchydy** [comment]
@mrlika sorry i forgot to mention i wasn't talking about the tracker, i meant what's server's requirements (bandwidth, cpu, line ...) to serve the actual live video. for the tracker i can use just azure or something.

**Comment by Er-rchydy** [comment]
ok thanks, i was just wondering if you have some informations about the required server to serve a video 520p to that number of users ( again not talking about the tracker, i'm talking about rtmp server ).
it's weird i searched about it for hours but i didn't find an article or someone talks about server requirements to serve live video to a lot of users.

**Comment by mrlika** [comment]
P2P Media Loader doesn't support RTMP. It supports segmented streams: HLS and DASH.

To host HLS or DASH you need HTTP server and you have to calculate bandwidth, CPU requirements of your HTTP server and CPU requirements of software that generates the stream (i.e. transcoding etc.)

But if you do not have horizontally scalable HTTP servers infrastructure I recommend for the 20k users test use a CDN and deliver HLS/DASH stream using it.

Because if your stream is 1 Mbps for 20k users in worst case they will download with 20 Gbps speed.

**Comment by Er-rchydy** [comment]
@mrlika  ok thanks, do you have any cheap CDN suggestions ?

**Comment by f1l1b0x** [comment]
@Er-rchydy check out wowza cloud they are using akamai and will allow you to use their cdn for 20.000 concurrent without any annual commitment but pay as you go

**Comment by Er-rchydy** [comment]
@f1l1b0x thanks, do you have any idea about how much it would cost, because i'm doing this for testing purposes. 
example:  video: 520p fixed, live for 2 hours, 20.000 visitors watching the whole live at the same time, how much it would cost at this scenario, average price of course
