### ISSUE TITLE
Cannot count the previous peers

### ISSUE THREAD

**Issue by nickcartery** [Novage/p2p-media-loader#61]
Hi,

Please try opening this link in 2 tabs: http://tv.vnoo.net/livetv/vh1/vh1.html
and open Network panel
![image](https://user-images.githubusercontent.com/10054833/55142432-2f66d980-516f-11e9-9750-28e86bc91dc5.png)

When PeerConnect is triggered, you can see tab 1 report that have 1 device is paired, but in the tab 2 is not.

TAB1:
![image](https://user-images.githubusercontent.com/10054833/55142268-d139f680-516e-11e9-904f-2c9d674f4f3d.png)

TAB2:
![image](https://user-images.githubusercontent.com/10054833/55142364-fe86a480-516e-11e9-84de-c5903427d680.png)

```
        engine.on(p2pml.core.Events.PeerConnect, function(peer){
            mem_peers.push(peer);
            console.log(peer);
        });

        //show the count devices in the update View function (has setInterval function in there):
        var total_peers = mem_peers.length;
        network_views.innerHTML = total_peers + (total_peers > 1 ? " devices" : " device");

```

It's caused by my wrong code or it's a bug?

Thanks,

**Comment by mrlika** [comment]
Most like you set the event handler after the peer is already connected.

And another advice - the stream will not share well over P2P because it has only 3 segments in the playlist.

Consider having 20 segments with 4-10 seconds duration for best P2P performance.

**Comment by mrlika** [comment]
P.S>
```JS
engine.on(p2pml.core.Events.PeerConnect, function() {console.log("CONNECTED");});engine.on(p2pml.core.Events.PeerClose, function() {console.log("CLOSED");});
```

I run the code directly in the browser's console right after the page loads and engine object exists. I see `CONNECTED` message but your network panel still shows 0 peers, while the peer is actually connected.

**Comment by nickcartery** [comment]
> Most like you set the event handler after the peer is already connected.
> 
> And another advice - the stream will not share well over P2P because it has only 3 segments in the playlist.
> 
> Consider having 20 segments with 4-10 seconds duration for best P2P performance.

Does it cause delay? I mean latency. 20 segments with 3 seconds duration for Live stream

**Comment by mrlika** [comment]
Yes. But is up to you to choose between shorter delay and better P2P ratio
