### ISSUE TITLE
Как должна выглядить функция segmentUrlBuilder?

### ISSUE THREAD

**Issue by supersh86** [Novage/p2p-media-loader#62]
Добрый день, решил воспользоваться вашим проектом. 
В моем плеере все ссылки динамические, плеер подгружает ссылку плейлиста video.php а там уже генерируется ссылки на уровни качества вместе с md5 защитой от хотлинка. 
Поэтому мне нужно создавать отдельный segmentID.
При изучении документации как я понял за это отвечает segmentUrlBuilder.

Я попробовал создать простой код 
```
segmentUrlBuilder:function (url) {
                console.log(url);
                return url;
                }
```
Но у меня ничего не получилось, было бы здорого если бы вы в документации привели полностью пример расширенной конфигурации через API с использованием синтаксиса. Спасибо!

**Comment by mrlika** [comment]
Для того, что-бы работало P2P для стрима необходимо выполнение нескольких условий:

- Пиры должны быть в одном сварме, т. е. у них должен быть одинаковый swarm ID. по умолчанию он равен URL мастер плейлиста без query. Если URL плейлиста для всех пользователей разный - устанавливайте swarmId в одно и то же значение для такого стрима вручную в конфигурации.
- Сами плейлисты должны быть с аналогичным контентом, т. е. одинаковое количество вариантов в одинаковом порядке, а в вариантах сегменты с одинаковыми EXT-X-MEDIA-SEQUENCE. URL вариантов и сегментов значения не имеют.

segmentUrlBuilder используется только для подмены URL сегмента, например если сегмент доступен на нескольких серверах для распределения нагрузки, для выбора ближайшего сервера и т. п.

**Comment by supersh86** [comment]
Спасибо за ответ. Сейчас более внимательно изучаю документацию.

**Comment by supersh86** [comment]
А есть ли привязка к адресу манифеста? Пользователь с манифестом n1 может скачать у пользователя с манифестом n2 если файлы индентичны?

**Comment by mrlika** [comment]
Да, как я описал выше

>  устанавливайте swarmId в одно и то же значение для такого стрима вручную в конфигурации

**Comment by supersh86** [comment]
хорошо, спасибо

**Comment by supersh86** [comment]
У меня еще один маленький вопрос. После установки вашего скрипта у hlsjs пропали данные о размере сегмента в байтах hls.streamController.fragCurrent.loaded всегда 0. В вашем скрипте можно как узнать размер сегмента?

**Comment by supersh86** [comment]
Всем привет. 
У меня вопрос, если у пользователей разный url сегмента, но 1 swarmid, смогут ли они между собой обмениваться данными? 
По моим тестам получается так что те кто качает с server 1 не могут обмениваться с теми кто качает с server2
хотя данные идентичны.

**Comment by supersh86** [comment]
Прошу прощения, изучив подробно проблему, убедился что swarm ID всетаки разный. Теперь подробно опишу проблему. 

Есть один сервер источник - orgin и есть 2 рестримера - s1 и s2.
Так как orgin генерирует плейлист, данные у s1 и s2 идентичны. 
s1 и s2 закладываются в hls манифест, я это сделал для нативной поддержки продуктов safari.
Так вот, в hlsjs я переключаю по инструкции разработчиков:
```
hls.levels[уровень].urlId = (0или1);
hls.levels[уровень].details = undefined;
```
hls.levels[уровень].url = ["s1", "s2"]

Так вот, при данном переключении swarm ID становиться не v0 или v1 как заданно в плейлисте, а v2, тоесть считает что переключен на 3 поток качества. 
Хотя в hls.levels только 2 уровня качества. 

Следовательно было 
480p = 0
720p=0
 А стало 
480p = 1
720p=2

Структура в самом hlsjs не поменялась, только изменился id url.

**Comment by supersh86** [comment]
При каждом переключении в p2p.segmentManager.variantPlaylists добавляется список.
