### ISSUE TITLE
bufferStalledError 

### ISSUE THREAD

**Issue by supersh86** [Novage/p2p-media-loader#63]
Добрый день. После установки p2p у меня появилась проблема с ошибками bufferStalledError на популярных vod потоках. 
Сначало происходит bufferStalledError, потом bufferNudgeOnStall, потом плеер стопориться и потом происходит bufferSeekOverHole.

![Imgur](https://i.imgur.com/r9l9tYe.png)

В среднем набирается по 10к ошибок за 30 мин.

Еще наблюдаются постоянные ошибки с трекерами.

**Comment by mrlika** [comment]
> Еще наблюдаются постоянные ошибки с трекерами.
Не используйте публичные трекеры для production. Подымите свой трекер и будьте независимы.

Для диагностики ошибок буферезации надо смотреть на сам HLS поток и конфигурацию. Без дополнительной информации помочь не могу.

**Comment by supersh86** [comment]
```
p2pConfig={
  segments:{
    swarmId:'<?php echo $_GET["vid"] ?>'
  },
  loader:{
  }
};
var p2p = new p2pml.hlsjs.Engine(p2pConfig);
  var hls = new Hls({
            //debug:true,
            maxBufferSize: 60000000,
            maxBufferLength: 60,
            abrBandWidthUpFactor:0.3,
            levelLoadingRetryDelay:10000,
            startLevel: +currentLevel,
            loader: p2p.createLoaderClass()

  })
  p2pml.hlsjs.initHlsJsPlayer(hls);
//p2p end
  hls.loadSource(source);
  hls.attachMedia(video);
```

Я не использую особых настроек. Просто когда пользовался cdnbye таких ошибок не наблюдал.

**Comment by supersh86** [comment]
Кажется я понял, я посчитал что стандартное кол сегментов в p2p равно 30, а это больше чем буффер hls. Вроде глюки пропали.

**Comment by supersh86** [comment]
а у вас есть какие нибудь функции которые останвливают загрузку?

**Comment by mrlika** [comment]
> а у вас есть какие нибудь функции которые останвливают загрузку?
кажется нет. над этим надо поработать :-) запишу себе в задачи.

> Или можно поменять параметр forwardSegmentCount после инциализации?
параметры динамически менять нельзя. возможно добавить изменение некорых, но опять же это в планах.
