### ISSUE TITLE
Don't use public trackers for production. 5k peers limit.

### ISSUE THREAD

**Issue by mrlika** [Novage/p2p-media-loader#64]
Use public trackers only for development and demonstrations. Run your personal tracker to go stable and independent: https://github.com/Novage/wt-tracker

I mostly addressing those guys:
```
origin: https://anime.anidub.com
origin: https://vidlink.org
origin: https://www.streamlive.to
```

**Comment by mullerivan** [comment]
We have a  Free but  Private  tracker  that  may  support over  500k viewers on the same  time,

feel free to contact US info@swarm.video

![Screenshot from 2019-04-13 11-43-33](https://user-images.githubusercontent.com/1794688/56081410-6f6ec300-5de3-11e9-983e-3a102c4de532.png)

**Comment by supersh86** [comment]
Руки еще не дошли.

**Comment by mullerivan** [comment]
Just need  to write and email we  compile one a custom Js  for you that  connect  our  tracker's servers 0 latency and scalable on demand,

**Comment by supersh86** [comment]
> @supersh86
> Just need to write and email,Then we compile a custom Js for you that connect our tracker's servers
> 
> 0 latency and scalable on demand,
This question is addressed to the author.

**Comment by mrlika** [comment]
You can run any WebTorrent tracker. This one will work: https://github.com/Novage/wt-tracker
It is WebSockets application.

Then specify your personal tracker in the configuration of the engine.

**Comment by supersh86** [comment]
> You can run any WebTorrent tracker. This one will work: https://github.com/Novage/wt-tracker
> It is WebSockets application.
> 
> Then specify your personal tracker in the configuration of the engine.

I launched, tracker and watch similar errors as your trackers. While the server load is less than 3%.

**Comment by mrlika** [comment]
Novage runs only one tracker and it can not respond 502 at all:

![Screenshot_20190413_230358](https://user-images.githubusercontent.com/1469266/56084780-e7b7a180-5e40-11e9-9fd2-3d52cd9050f2.jpeg)

**Comment by mrlika** [comment]
Other trackers are from https://openwebtorrent.com/ project.

**Comment by supersh86** [comment]
@mrlika Мы наверно всетаки не понимаем друг друга. Я установил сервер который был по ссылке. У него к сожалению нет документации к настройкам. У меня вопрос собвственно что обозначают настройки 

```
      "websockets": {
        "path": "/*",
        "maxPayloadLength": 65536,
        "idleTimeout": 240,
        "compression": 1
      }
    }
  ],

  "tracker": {
    "maxOffers": 20,
    "announceInterval": 220
  },
```
А так же есть ли настройки таймаута в самом движке p2p, которые умешат кол запросов от пользователя.

**Comment by mrlika** [comment]
See updated [documentation](https://github.com/Novage/wt-tracker/blob/master/README.md#configuration). Looks like `announceInterval` is what you need - it controls announce requests frequency on the clients.

**Comment by ppoot** [comment]
I built a wt-tracker,Please delete my domain. Thank you.
