### ISSUE TITLE
How to change STUN servers?

### ISSUE THREAD

**Issue by thenikin** [Novage/p2p-media-loader#65]
Hi there, i'm getting a lot of ICE errors while debugging. I think it's related to bad STUN servers. Is there any easy way to change them in code without having to edit the npm packages?

Thanks

**Comment by mrlika** [comment]
Do it in settings of an engine: https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-hlsjs#engine--new-enginesettings

**Comment by thenikin** [comment]
Thanks, but is there any way to hardcode this into source when building?

**Comment by mrlika** [comment]
Yes. Just hardcode whatever you want. It's HybridLoader setting.
