### ISSUE TITLE
Rapid Peer dropoff 

### ISSUE THREAD

**Issue by kyle170** [Novage/p2p-media-loader#66]
I just had a stream with 300+ clients connected and the p2p worked flawlessly, however near the end of the stream (last minute) over half of the clients disconnected due to the end of the stream which caused a massive peer drop-off which caused the stream to pretty much go offline for the remainder of the connected clients. Is there a way to assist a rapid peer drop-off and help the remainder of the streams to function normally?

Stream is HLS x264 with 3 second segments with a 60s playlist

**Comment by mrlika** [comment]
What player are you using?

**Comment by kyle170** [comment]
Clappr

**Comment by mrlika** [comment]
I tested the demo with a VOD stream in Clappr. It keeps streaming P2P even after the stream ended - I manually move playhead position to the end of the stream.

**Comment by kyle170** [comment]
I will run a 800+ client stream test over the weekend and report back more detailed findings to see if this happens again

**Comment by mrlika** [comment]
Peer dropoff may happen because peers just leave the page.

**Comment by kyle170** [comment]
That is correct, is there a recommended settings for preventing a client from loosing mostly all or all of its p2p peers and being able to continue using the source without buffering? Will adjusting p2p timeout length optimization, stream chunk length or other settings see a benefit in this scenario?

**Comment by mrlika** [comment]
The library should not perform worth than a player without P2P. Most likely the source bandwidth is not enough for all those visitors when peers are leaving the page.

**Comment by kyle170** [comment]
Issues did not appear in today's stream and are no longer happening after switching to a private tracker... Closing issue
