### ISSUE TITLE
Segment downloadSpeed

### ISSUE THREAD

**Issue by supersh86** [Novage/p2p-media-loader#67]
Добрый день, у меня вопрос по этому показателю, учитывается ли pending (время отклика) при подсчете загрузки сегмента, или скорость считается со старта загрузки? 

Если учитывается скорость только со старта загрузки без учета пендинга, то это может дать ошибочное представление о скорости загрузки файла. 
При сильных нагрузках у сервера видео может быть очень долгое время отклика. 
![Imgur](https://i.imgur.com/7tp7mad.png)

**Comment by mrlika** [comment]
P2P Media Loade способен загружать несколько сегментов одновременно, некоторые в случайном порядке. Что и как грузить решает алгоритм, исходя из текущей ситуации, что бы проигрование было без буферизаций и при этом по-больше загрузить по P2P.

Hls.js и Shaka Player движки расчитаны только на последовательную загрузку сегментов.

По этому мы рапортуем им расчетное время загрузки сегмментов, исходя из статистики полученых байт от P2P и HTTP загрузок за небольшой промежуток времени.

При таком подходе понятие время отклика теряется, но в общем оно учитывается в этой статистике.

**Comment by supersh86** [comment]
@mrlika а это касается ситуации когда нет p2p пиров и загрузка идет полностью с http?

**Comment by mrlika** [comment]
Да

**Comment by supersh86** [comment]
Я провел анализ данных и нашел расхождение.

Возмем 1(2) сегмент
![Imgur](https://i.imgur.com/vpOvkZ0.png)
Он закачался за 1.85s
![Imgur](https://i.imgur.com/es5tkby.png)
Его размер 2.7mb или 2814000 байт
![Imgur](https://i.imgur.com/gLkKvC1.png)
Ваша система определила что он загрузился со скоростью 2457,6 байт в миллесекунду
![Imgur](https://i.imgur.com/4dtG8s5.png)

Переводим все в миллесекунды и в байты 

size 2814000
bweHls 18014752613
bwspeedP2Pengine 2457,6
timeallChrome 1850
timeafterpendChrome 1700

Сразу видно что Bwestimate ошибочен, а файл по вашей версии загрузился за 1145мс

**Comment by mrlika** [comment]
Ваши суждения ошибочны, потому что основываются на мнении, что грузился всего один сегмент (собственно плееры так и думают). А на самом деле вместе с этим сегментом грузились другие сегменты одновременно.

И вполне логично, что надо сообщать скорость загрузки не одного сегмента, а всех сегментов одновременно (скорость гибридной P2P + HTTP сети).

Иначе скорость будет занижена и проигрование будет на более низком качестве.

**Comment by supersh86** [comment]
Прошу прощение, не уточнил
стояла настройка simultaneousHttpDownloads:1

**Comment by mrlika** [comment]
P2P загрузки тоже надо учитывать?

**Comment by supersh86** [comment]
@mrlika их не было, я специально тестировал на файле где нет пиров. И в статистике не было p2p загрузок. Я бы не стал писать эту тему если бы сам все не проверил. Смысл лишний раз вас отвлекать?

**Comment by mrlika** [comment]
Понятно. Такое действительно может быть, когда один пир на стриме, а учета задержки ответа нет. Я подумаю, что можно сделать. Здесь сложность в том, что алгоритм должен работать и для нескольких одновременных загрузок сегмента тоже.

**Comment by supersh86** [comment]
@mrlika спасибо. Будем ждать обновлений.

**Comment by supersh86** [comment]
@mrlika как оказалось для онлайна больше 5к как то тяжело оказалось 2 потока по http, наверно это всетаки больше подходит для live где меньше запросов к дисковой подсистеме. Пришлось отключить. Еще увидел странную закономерность, при включении настройки **httpDownloadProbabilitySkipIfNoPeers** загрузка происходит только 1-2 сегмента вперед, вместо 10 как если бы значение стояло на false.

**Comment by mrlika** [comment]
> 1-2 сегмента вперед

Да. В этом случае грузятся только required сегменты. Нужно увеличить requiredSegmentsPriority. Я подумаю, как можно будет улучшить алгоритм в такой ситуации.

**Comment by mrlika** [comment]
Всетаки в таком случае лучше увеличить requiredSegmentsPriority. Это обязательный буфер который поддерживается для стабильного проигрования.

**Comment by supersh86** [comment]
@mrlika а возможность начально предзагрузки есть, если предположим перед запуском плеера я хочу загрузить только 1 сегмент. Это делается для экономии лишнего трафика, когда пользователи отрывают страницу и не запускают плеер, что бы почитать описание или пообщатся в комментах.

**Comment by Vladislavik** [comment]
requiredSegmentsPriority поставьте тогда 1

**Comment by supersh86** [comment]
@Vladislavik 
Уже пробовал, при загрузке страницы, он его игнорирует.

**Comment by mrlika** [comment]
Если не важен мгновенный запуск видео попробуйте использовать httpDownloadInitialTimeout, httpDownloadInitialTimeoutPerSegment.

P. S.
В других темах будем переходить на английский, так как обсуждаемая информация должна быть доступна сообществу для понимания и обсуждения.

**Comment by Vladislavik** [comment]
У меня загружает до httpDownloadMaxPriority и останавливается preload=“auto” в плеере

**Comment by supersh86** [comment]
@mrlika Спасибо попробую. 
PS.
хорошо, тогда давайте оставим этот тред для русскоговорящих.

**Comment by supersh86** [comment]
@Vladislavik спасибо, попробую.

**Comment by supersh86** [comment]
@mrlika Привет.
Можете сказать, есть возможность как то ограничить кол одновременным подключений p2p? После 100 пользователей, процессор начинает ощутимо нагружатся.

**Comment by mrlika** [comment]
Такой возможности нет. Подумаю, как это  правильно сделать в ближайшее время. Просто ограничивать не вариант. Если лимит, например, в 9 пиров, то есть большая вероятность, что 11й пир просто нискем не соединится со старта, так как 10 предыдущих уже соединились между собой (1 к 9ти) и больше в свой рой никого не пустят.
