### ISSUE TITLE
Don't support ios10.3

### ISSUE THREAD

**Issue by ppoot** [Novage/p2p-media-loader#69]
Hello, the test found that IOS 10.3 and the following version are not supported.Player blank.
Is there a solution?

**Comment by mrlika** [comment]
Yes. It is not possible to run the technology on iOS in browsers. Solution - request from Apple Media Source Extensions support on iOS.

This is the limitation of all existing P2P video streaming solutions.

**Comment by mrlika** [comment]
Support Table: https://github.com/Novage/p2p-media-loader#web-browsers-support
Can I use...: https://caniuse.com/#feat=mediasource

**Comment by ppoot** [comment]
I don't want it to support P2P, It's a problem that 10.3 can't load the players .
![111](https://user-images.githubusercontent.com/29155990/56282821-9d853780-6142-11e9-9c31-b4c418bdd5bd.jpg)

**Comment by mrlika** [comment]
Check errors in the browser console. I don't have iOS 10.3 to test.

**Comment by ppoot** [comment]
I know it through the reaction of visitors, I tested it with the online IOS tool.
https://appetize.io/demo?device=iphone6s&scale=75&orientation=portrait&osVersion=9.3
So can't check the console.

**Comment by mrlika** [comment]
Probably the .js file can not be parsed by old browser. Check that `p2pml` and `p2pml.hlsjs` exist before doing `p2pml.hlsjs.Engine.isSupported()` check.

**Comment by ppoot** [comment]
There's a similar project that supports IE and old browsers calling players.
You can refer to it? https://github.com/cdnbye/hlsjs-p2p-engine

**Comment by mrlika** [comment]
We are talking about different things. The problem is not in P2P Media Loader. It is up to you how to integrate player so it works on all browsers.

**Comment by mrlika** [comment]
P2P Media Loader libarary should not be called in old browsers because any way they do not support P2P.

**Comment by ppoot** [comment]
So how to write the script? are there any examples? 
players will also be loaded when browsers do not support P2P.
I saw Engine don't know much about it.

**Comment by yoaviwe** [comment]
Not true. Peer5 supports p2p on any ios browser.

**Comment by mrlika** [comment]
You can find examples in the documentation and in the demo.

If the script is loaded (`p2pml` and `p2pml.hlsjs exist`) and `p2pml.hlsjs.Engine.isSupported()` returns true you can configure a player with the P2P Media Loader.

In other cases just run a player without P2P Media Loader.

**Comment by ppoot** [comment]
```
<script>
        if (p2pml.hlsjs.Engine.isSupported()) {
            var engine = new p2pml.hlsjs.Engine();
            var player = new Clappr.Player({
                parentId: "#video",
                source: "https://akamai-axtest.akamaized.net/routes/lapd-v1-acceptance/www_c4/Manifest.m3u8",
                playback: {
                    hlsjsConfig: {
                        liveSyncDurationCount: 7, // To have at least 7 segments in queue
                        loader: engine.createLoaderClass()
                    }
                }
            });
            p2pml.hlsjs.initClapprPlayer(player);
            player.setVolume(1); // 1%
            player.play();
        } else {
            var player = new Clappr.Player({
                parentId: "#video",
                source: "https://akamai-axtest.akamaized.net/routes/lapd-v1-acceptance/www_c4/Manifest.m3u8",
    });
        }
    </script>
```
It doesn't work. “p2pml”undefined

**Comment by mrlika** [comment]
And what keeps you from adding the check for undefined?

**Comment by ppoot** [comment]
I execute in ie11, p2pml undefined, else is abandoned

**Comment by mrlika** [comment]
Yes. Because in version 0.3.0 we switched to ES6 and now the JavaScript code fails to execute in old browsers. But any way P2P doesn't work in those browsers and the library is not needed there.

Just do the check like:

```javascript
if (p2pml && p2pml.hlsjs.Engine.isSupported()) {
```

**Comment by mrlika** [comment]
iOS 13 should support MSE and P2P
