### ISSUE TITLE
404 .ts segment 

### ISSUE THREAD

**Issue by kabsila** [Novage/p2p-media-loader#7]
Hi
when .ts segment is loading it get 404 error sometimes.
What is the reason ?
How to fix it or config something ?

**Comment by mrlika** [comment]
Hi,

Do you mean HTTP 404 Not Found error? Looks like a segment is requested but it doesn't exist. It can be a problem with the segmented stream itself.

Is it HLS or DASH stream?
Can you share the stream so we can check? (Preferable on Monday)

**Comment by kabsila** [comment]
Yes, I mean HTTP 404 Not Found error.
It is HLS.
Sorry, I can’t share the stream but I’m pretty sure it not a problem with stream itself.
I have tested with another comercial p2p-loader and it no 404 error.
How could this problem happens?

![screen shot 2561-09-23 at 12 48 30 pm](https://user-images.githubusercontent.com/5105982/45924678-5d553200-bf30-11e8-8c59-96ce9934d355.png)

![screen shot 2561-09-23 at 12 48 46 pm](https://user-images.githubusercontent.com/5105982/45924681-71009880-bf30-11e8-90d7-168e751f206a.png)

**Comment by kabsila** [comment]
The stream have a problem with the segmented itself. 
Thank you.
