### ISSUE TITLE
Different versions are not compatible?

### ISSUE THREAD

**Issue by amtbnagios** [Novage/p2p-media-loader#70]
Version 0.2.1 & 0.50 seems not compatible, 0.50 client can't get p2p from 0.2.1 client!

**Comment by mrlika** [comment]
You are right. The P2P communication protocol was optimized in 0.5.0 and it doesn't connect with earlier versions.

**Comment by amtbnagios** [comment]
Thanks a lot!

**Comment by amtbnagios** [comment]
Thanks a lot!
