### ISSUE TITLE
jwplayer control is not hide

### ISSUE THREAD

**Issue by littlesker** [Novage/p2p-media-loader#73]
I use jwplayer's P2P service, but now the control bar can't be hidden, which is really unacceptable for an obsessive-compulsive disorder. I try to modify the code, but it doesn't work. Unless I don't use p2p, what's wrong with the code? Here's a demonstration
https://jsfiddle.net/hmyapb2n/2/

**Comment by mrlika** [comment]
There is no such problem in the demo: https://novage.com.ua/p2p-media-loader/demo.html?type=jwplayer

You can try to start from the simplest code that works: https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-hlsjs/demo/jwplayer.html

**Comment by littlesker** [comment]
thank you，but If I replace it with this file  ：https://cn2.78love.cn/hls/20190403/1ffc8bde5138e793f177751aa9ff2a37/1554301371/index.m3u8
, that problem will arise.

**Comment by mrlika** [comment]
I think there is a problem with your stream. It sometimes work but sometimes gives the error:
````
curl https://cn2.78love.cn/hls/20190403/1ffc8bde5138e793f177751aa9ff2a37/1554301371/index.m3u8
<html><head><title>ERROR: ACCESS DENIED</title></head><body><center><h1>ERROR: ACCESS DENIED</h1></center><hr>
<center>Fri, 26 Apr 2019 15:16:29 GMT (taikoo/BC23_dx-jiangsu-yancheng-3-cache-4)</center></BODY></HTML>
<!-- web cache -->
```

**Comment by mrlika** [comment]
It is a problem with Hola jwplayer-hlsjs provider. It is reproducible with your stream without P2P:
```
var player = jwplayer("player");
player.setup({
  file: "https://cn2.78love.cn/hls/20190403/1ffc8bde5138e793f177751aa9ff2a37/1554301371/index.m3u8"
});
var provider = require("@hola.org/jwplayer-hlsjs");
provider.attach();
```
You have to report the issue here: https://github.com/hola/jwplayer-hlsjs

**Comment by Yokutto** [comment]
This is a problem with Hola provider, the CDNBye also use this provider for jwplayer and have similar problem in [this issue]( https://github.com/cdnbye/hlsjs-p2p-engine/issues/16#issue-349370877). The Hola provider seems to be stable with Jwplayer v8.0.11.

If you want to use P2P with latest version of jwplayer, consider using a "closed-source" provider, like streamroot or peer5. You can test it for free, but it don't have a "free user plan"

**Comment by AntonShchemelev** [comment]
The controls don't hide with Hola hls.js provider for JWPlayer when there is no master manifest in the stream. Add master manifest and the controls will hide.

**Comment by AntonShchemelev** [comment]
Created pull request to fix the issue: https://github.com/hola/jwplayer-hlsjs/pull/3

**Comment by mrlika** [comment]
Original repository looks dead.

You can use our fork. The issue with not hiding controls is fixed there.

Repository: https://github.com/Novage/jwplayer-hlsjs

Run:
```
git clone https://github.com/Novage/jwplayer-hlsjs
cd jwplayer-hlsjs
npm install
npm run build
```

Then you can find JS library in `dist` directory.
