### ISSUE TITLE
Seek back not work

### ISSUE THREAD

**Issue by nemesisqp** [Novage/p2p-media-loader#74]
- My setup combination is Clappr + shaka-playback + p2p (core, shaka), the problem is seeking back don't work, seek forward work though.
- I'm created a repository demostrate the problem here [clappr-shaka-p2p-bug](https://github.com/nemesisqp/clappr-shaka-p2p-bug) ```http://localhost:17001/static/index.html```
- I'm tested with both cdn 0.5.0 and my custom build of p2p-loader (just some modify to url mapping range header to querystring so I can avoid CORS problem)
- The video is encoded to dash fragmented mp4 by facebook so there should be fine.
- The combination player without p2p-loader worked fine when I disabled p2p [here](https://github.com/nemesisqp/clappr-shaka-p2p-bug/blob/83935307dcc2c365a6024a16d9a62da3a8d6715a/static/p2p-player.js#L108)
- I don't know where to look next.

**Comment by mrlika** [comment]
I have no issues seeking in any direction. I am testing Shaka's demo stream https://storage.googleapis.com/shaka-demo-assets/sintel/dash.mpd in our demo:

http://novage.com.ua/p2p-media-loader/demo.html?url=https%3A%2F%2Fstorage.googleapis.com%2Fshaka-demo-assets%2Fsintel%2Fdash.mpd&type=shakaplayer

**Comment by nemesisqp** [comment]
I just tested, that shaka demo stream worked fine, I will swap those video later
