### ISSUE TITLE
p2p-media-loader supports videojs-http-streaming (VHS)?

### ISSUE THREAD

**Issue by raestrada95** [Novage/p2p-media-loader#75]
Hello, as the title says p2p-media-loader supports videojs-http-streaming (VHS)?, I can not find any way to make it work, I thank you in advance for any help.

**Comment by mrlika** [comment]
The library doesn't support it. Also, my tests show that VHS is not so good as Hls.js and Shaka Player engines.
Use video.js with hlsjs-contrib plugin.

**Comment by raestrada95** [comment]
Thanks for the reply., I said it because as it says hlsjs-contrib will be disused, but I will try to implement hlsjs-contrib .

**Comment by Chocobozzz** [comment]
In peertube we use https://github.com/streamroot/videojs-hlsjs-plugin with hls.js: https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/player/peertube-player-manager.ts#L210

**Comment by mrlika** [comment]
We also added support of Streamroot hls.js plugin for video.js in d038e15fe82651d07e8263c1d35691dccdf70ccb that will be included into next release.
See `initVideoJsHlsJsPlugin` function. It is very similar to the plugin from Peer5.

**Comment by mrlika** [comment]
> Thanks for the reply., I said it because as it says hlsjs-contrib will be disused, but I will try to implement hlsjs-contrib .

I think you mean https://github.com/videojs/videojs-contrib-hls that is going to be disused. It has no relation to hls.js. It is actually VHS plugin that is laready built into video.js.

We integrate hls.js into video.js using plugins, that are not going to be disused:
- https://github.com/Peer5/videojs-contrib-hls.js/
- https://github.com/streamroot/videojs-hlsjs-plugin

**Comment by jl91569** [comment]
> I think you mean https://github.com/videojs/videojs-contrib-hls that is going to be disused. It has no relation to hls.js. It is actually VHS plugin that is already built into video.js.
> 
> We integrate hls.js into video.js using plugins, that are not going to be disused:

Since it's possible to override the XHR loader used in videojs-http-streaming, would it be theoretically possible to implement support for it to remove dependencies on external plugins? If so, would you mind telling how much work you think it would take?

I'm currently using the Peer5 plugin as it's the best for my use-case but I'm worried it won't work in future releases because it hasn't seen any commits for nearly 1.5 years now (I can't find an easy, reliable way to build a quality switcher for the Streamroot plugin).

**Comment by mrlika** [comment]
We will try to support hls.js in video.js player. What quality selector are you using?

**Comment by jl91569** [comment]
I built my own one that directly hooks into hls.js instead of using a prebuilt one (I'm aware this is discouraged but it's better on mobile and easier to move between engines).

I only just found out that the Streamroot plugin supports videojs-contrib-quality-levels, so I might try to rebuild it around that though. Thank you for developing an excellent P2P plugin, and sorry about wasting your time with this :(

**Comment by mrlika** [comment]
We already support Streamroot plugin. It looks better and more actively developed: https://github.com/streamroot/videojs-hlsjs-plugin

And it supports https://github.com/videojs/videojs-contrib-quality-levels in the same way as VHS does.

In theory any quality selector plugin that  that uses API from this `videojs-contrib-quality-levels` should work with `streamroot/videojs-hlsjs-plugin + videojs-contrib-quality-levels` too.

**Comment by jl91569** [comment]
> We already support Streamroot plugin. It looks better and more actively developed: https://github.com/streamroot/videojs-hlsjs-plugin

Right, what I meant to say was that I had previously tried to reimplement my quality selector into the Streamroot plugin without `videojs-contrib-quality-levels` (I didn't realise it supported it as it wasn't on the list) and I ended up going back to the Peer5 plugin.

It'd still definitely be nice to have support for `videojs-http-streaming`, but I'll use the Streamroot plugin if you're planning to only support hls.js and Shaka for now.

Thanks for your help, I really appreciate it :)

**Comment by mrlika** [comment]
This one works: https://github.com/jfujita/videojs-http-source-selector

But you have to run `streamroot/videojs-hlsjs-plugin + videojs-contrib-quality-levels` and configure all with P2P. streamroot/videojs-hlsjs-plugin integration with P2P available in master.

**Comment by jl91569** [comment]
Thanks for the link, I've ported my quality selector over to `videojs-contrib-quality-levels` and the Streamroot plugin but I'll keep that in mind if I need a prebuilt one.

**Comment by mrlika** [comment]
we integrated jfujita/videojs-http-source-selector quality selector for video.js into our demo. we will publish it to our site with next release.
