### ISSUE TITLE
Can you please support Dplayer?

### ISSUE THREAD

**Issue by wslsq** [Novage/p2p-media-loader#76]
[Dplayer Github](https://github.com/MoePlayer/DPlayer)

Dplayer is an open source player and popular in china.

This project is very great. Thank you!

**Comment by mrlika** [comment]
I think it is rather easy. I will let you know once we are done.

**Comment by mrlika** [comment]
The player is already supported. I created a small demo of how to do it with HLS and P2P: https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-hlsjs/demo/dplayer.html

We will try to do MPEG-DASH with DPlayer demo shortly.

**Comment by mrlika** [comment]
DPlayer with MPEG-DASH and P2P support via Shaka Player engine demo: https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-shaka/demo/dplayer.html

**Comment by wslsq** [comment]
Thank you so much!
