### ISSUE TITLE
Property 'downloadBandwidth' does not exist on type 'Segment'.

### ISSUE THREAD

**Issue by taojishou** [Novage/p2p-media-loader#79]
> p2p-media-loader-hlsjs@0.5.0 build /opt/p2p-media-loader/p2p-media-loader-hlsjs
> npm run compile && npm run browserify && npm run minify

> p2p-media-loader-hlsjs@0.5.0 compile /opt/p2p-media-loader/p2p-media-loader-hlsjs
> tsc && copyfiles -f ./lib/*.js ./dist

lib/segment-manager.ts:242:75 - error TS2339: Property 'downloadBandwidth' does not exist on type 'Segment'.
242             this.segmentRequest.onSuccess(segment.data!.slice(0), segment.downloadBandwidth);
                                                                              ~~~~~~~~~~~~~~~~~

lib/segment-manager.ts:290:27 - error TS2554: Expected 2-6 arguments, but got 8.

290             segments.push(new Segment(
                              ~~~~~~~~~~~~
291                 id,
    ~~~~~~~~~~~~~~~~~~~
...
296                 (initialSequence + i).toString(),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
297                 byterangeToString(byterange), priority++));
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 2 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! p2p-media-loader-hlsjs@0.5.0 compile: `tsc && copyfiles -f ./lib/*.js ./dist`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the p2p-media-loader-hlsjs@0.5.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-03T16_14_38_167Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! p2p-media-loader-hlsjs@0.5.0 build: `npm run compile && npm run browserify && npm run minify`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the p2p-media-loader-hlsjs@0.5.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-03T16_14_38_240Z-debug.log

**Comment by mrlika** [comment]
Most likely you are building hls.js integration from `master` branch. In this case you have to link locally with `p2p-media-loader-core` from `master`. You can use `npm link` for that.

**Comment by taojishou** [comment]
I've executed NPM link, but the problem is still there

**Comment by mrlika** [comment]
Please check that `p2p-media-loader-hlsjs/node_modules/p2p-media-loader-core` is symlink to `p2p-media-loader-core` directory.

Also, we are going to release the new version soon.

**Comment by mrlika** [comment]
New version released
