### ISSUE TITLE
p2pml.hlsjs.initVideoJsHlsJsPlugin() is not a function

### ISSUE THREAD

**Issue by hossamnoaman153** [Novage/p2p-media-loader#80]
hello,

iam facing an error p2pml.hlsjs.initVideoJsHlsJsPlugin() is not a function
i have checked your hlsjs code this function doesn't exist!

thanks

**Comment by mrlika** [comment]
It doesn't exist in the latest release (version 0.5.0). It exists in the `master` branch: https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-hlsjs/lib/index.ts#L53

You have to build from the latest sources to use it or wait for the next release. I hope it will happen very soon.

**Comment by hossamnoaman153** [comment]
> It doesn't exist in the latest release (version 0.5.0). It exists in the `master` branch: https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-hlsjs/lib/index.ts#L53
> 
> You have to build from the latest sources to use it or wait for the next release. I hope it will happen very soon.

i can't wait my servers so overloaded.
i will try to build sources .

thanks

**Comment by hossamnoaman153** [comment]
`lib/segment-manager.ts:243:75 - error TS2339: Property 'downloadBandwidth' does not exist on type 'Segment'.

243             this.segmentRequest.onSuccess(segment.data!.slice(0), segment.downloadBandwidth);
                                                                              ~~~~~~~~~~~~~~~~~

lib/segment-manager.ts:298:17 - error TS2554: Expected 2-6 arguments, but got 8.

298                 byterangeToString(byterange), priority++));
`
Failed to build sources..

**Comment by mrlika** [comment]
If you build locally latest version p2p-media-loader-hlsjs and p2p-media-loader-shaka have to be linked with p2p-media-loader-core directory, not NPM package.

Use `npm link` command. If everything done correctly `p2p-media-loader-hlsjs/node_modules/p2p-media-loader-core` is symlink to `p2p-media-loader-core` directory.

**Comment by hossamnoaman153** [comment]
> If you build locally latest version p2p-media-loader-hlsjs and p2p-media-loader-shaka have to be linked with p2p-media-loader-core directory, not NPM package.
> 
> Use `npm link` command. If everything done correctly `p2p-media-loader-hlsjs/node_modules/p2p-media-loader-core` is symlink to `p2p-media-loader-core` directory.

Builded successfully 

Thanks a lot
