### ISSUE TITLE
use manifest "dynamically" file name as swarmId

### ISSUE THREAD

**Issue by hossamnoaman153** [Novage/p2p-media-loader#81]
hello,
iam using videojs with hlsjs plugin

in case of using multiple cdns urls i will have to set swarmId to specific id "because they are the same segments and video just another urls"
but if videojs changed video quality the same swarmId will still same!
in such event swarmId must be changed, it can't be the same for all manifest qualities

in my case manifest file name and its segments name are unique and is the same name on multiple cdn so how can i make p2p core using manifest file name only instead of full url for setting swarmId?

thanks

**Comment by mrlika** [comment]
We use WebTorrent tracker to gather peers into swarms. All peers that watch the same quality use the same info_hash. If quality changes - info_hash also changes. Peers that currently watch different qualities are not connected.

So:
- swarm ID is the ID of the stream with all qualities
- internally each quality has its own info_hash that is used to gather peers into swarms

**Comment by hossamnoaman153** [comment]
> * info_hash

info_hash generating using full url not only requested manifest file name
how i can make it generating only using manifest file instead of full url?
https://example.com/6h48fg4efasdf.m3u8
i need it to be generated using 6h48fg4efasdf.m3u8 only not full url because iam having multiple cdn using different urls but same file name

thanks

**Comment by mrlika** [comment]
In this case you can specify swarmId manually in configuration. By default it equals to manifest  URI.

**Comment by hossamnoaman153** [comment]
> In this case you can specify swarmId manually in configuration. By default it equals to manifest URI.

i can't because there are multiple quality for this video
if you could add an option to control how swarmId automatically generating would be better for a lot of people. choosing between full url and only file name

**Comment by mrlika** [comment]
You can set it in configuration and it means that you also can automatically generated it. Read the FAQ for better understanding: https://github.com/Novage/p2p-media-loader/blob/master/FAQ.md#what-are-the-requirements-to-share-a-stream-over-p2p
