### ISSUE TITLE
HLS with fmp4 works?

### ISSUE THREAD

**Issue by raestrada95** [Novage/p2p-media-loader#82]
Hi, I wonder if any of you know if it works with HLS fmp4 (m4s)  . Thx for the help!

**Comment by mrlika** [comment]
Hi, it should work.
But it depends on Hls.js or Shaka Player engines. If they support the format then it should work.
P2P Media Loader is responsible for delivering the segments and putting them correctly into the engines. And is not responsible for how the data is interpreted then.
