### ISSUE TITLE
Android chrome not start

### ISSUE THREAD

**Issue by supersh86** [Novage/p2p-media-loader#83]
Hi, after the update, there was a problem with playing on the android device via Chrome.
Tested through your demo.

Adroid ver 9, mobile Xiaomi mi 9. Last chrome.

**Comment by mrlika** [comment]
Just tested - works fine on my Nexus 5X. I will test on other devices tomorrow.

**Comment by mrlika** [comment]
Tested with Chrome on Xiaomi Mi 5, Meizu 9 and Nexus 5X. Everything good. All the devices interconnected.

**Comment by supersh86** [comment]
![Imgur](https://imgur.com/Za6Ur9c)
Странно

**Comment by mrlika** [comment]
Looks like a network error that is not related to P2P.  Manifests (.m3u8) should be downloaded over HTTP to start playback.
