### ISSUE TITLE
[Question] Approach of implementing P2P loader for Shaka

### ISSUE THREAD

**Issue by sapolio** [Novage/p2p-media-loader#84]
Приветствую! У вас замечательный проект!
Не могли бы вы помочь мне советом?
У меня есть задача сделать свою версию p2p для Shaka, но, поскольку новичок в TS и не работал с Shaka прежде, испытываю в этом немалые сложности )
Уже есть библиотека p2p/CDN загрузчика, который умеет, условно, только _loadFragment(context, callbacks)_ и _abortLoading()._
В HLSJS оказалось достаточно подменить штатный загрузчик, но тут...
Мне бы очень помог абстракный план из минимально необходимых шагов для самой базовой интеграции в Shaka подобного загрузчика.

**Comment by mrlika** [comment]
Hi,

To download over P2P you have to override network plugin.

But player downloads segments sequentially while efficient P2P algorithms require random download abilities. You have to download over P2P randomly ahead of player requests foreseeing next segments to be downloaded. That is why you have to know the data from manifest (HLS or DASH) that includes all the available segments and media variants. To do it we override manifest parser: https://shaka-player-demo.appspot.com/docs/api/shaka.extern.ManifestParser.html.

From HTMLMediaElement you can get current playing position.

And when you know the current playing position, segments that are currently requested by the player, list of all the segments and media variants from manifest you can build your efficient P2P algorithm that will plan HTTP and P2P downloads to play the video without stalls.

**Comment by sapolio** [comment]
Thank you a lot for your answer!
Sorry for speaking russian
This is because I saw you have another issue in russian.

**Comment by mrlika** [comment]
That's fine. The information can be helpful to others. I may need to reference it. That is why I try to keep conversations in English.
