### ISSUE TITLE
Does not work in Firefox Linux

### ISSUE THREAD

**Issue by renatofrota** [Novage/p2p-media-loader#85]
Hello,

it is not working in Firefox Linux.

`Exit UDP socket connected

UDP socket error:Internal error at /build/firefox-BlSS22/firefox-68.0.2+linuxmint1+tina/dom/network/UDPSocketParent.cpp:269 this=0x7ff943276800

ICE(PC:1566223313675441 (id=34359738392 url=http://novage.com.ua/p2p-media-loader/demo.html)): relay/proxy only option results in ICE TCP being disabled

ICE(PC:1566223313675441 (id=34359738392 url=http://novage.com.ua/p2p-media-loader/demo.html)): couldn't create any valid candidates

ICE(PC:1566223313675441 (id=34359738392 url=http://novage.com.ua/p2p-media-loader/demo.html)): peer (PC:1566223313675441 (id=34359738392 url=http://novage.com.ua/p2p-media-loader/demo.html):default) has no stream matching stream PC:1566223313675441 (id=34359738392 url=http://novage.com.ua/p2p-media-loader/demo.html) transport-id=transport_0 - a9557e52:c97a6a09f39e69a8f392f951858ba23a`

Firefox 68.0.2, x86_64 Linux 5.0.0-23-generic (Mint 19.1)

Works fine in Chrome.

Any idea what may be the issue?

**Comment by mrlika** [comment]
Works in FF from Linux Mint 18.3 and Ubuntu for me

**Comment by renatofrota** [comment]
I have disabled all FF extensions and it works.

Strangely, I have re-enabled all the extensions again (one by one, trying to find which could be causing the issue) and it still works after all extensions are re-enabled.

Thank you for this awesome project.

Quick question: are HLS segments shared only after fully downloaded or do *parts* of segments also get uploaded to others?

My problem is resolved so you are free to close this =]

**Comment by mrlika** [comment]
Only full segments are shared
