### ISSUE TITLE
What's the segment download policy?

### ISSUE THREAD

**Issue by motea927** [Novage/p2p-media-loader#86]
Excuse me, What's the segment download policy?
I know this project will cut segment to many smaller pieces,
Can this project download same segment but from difference peer(difference pieces)?
I can't find any code, It look's like download same segment from one peer, but same time can download different segments from differing peer

**Comment by mrlika** [comment]
Segments are not split into pieces.

A segment is downloaded from one peer at a time. If the download fails the segment may be downloaded from another peer.

Few simultaneous P2P downloads are supported each from different peer.

**Comment by motea927** [comment]
Thanks your answer, this is very useful
