### ISSUE TITLE
Return built segment url on HTTP error

### ISSUE THREAD

**Issue by Chocobozzz** [Novage/p2p-media-loader#87]
Hi,

When we setup a URL segment builder, and there is a [HTTP segment error event](https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-core/lib/http-media-manager.ts#L190) fired, we don't know what was the real segment URL specified in the XHR request. Without this, it's more difficult for us to not specify the same bad host in future other segment requests.

We could add an additional parameter in the `Events.SegmentError` callback function, but I don't know if we should update the first parameter (that is a `Segment`) to be an object `{ segment, xhrUrl }`  or if we should add a third optional parameter.

**Comment by mrlika** [comment]
Hi,

Good point. I think we can add requestUrl and responseUrl optional fields to the segment.

**Comment by mrlika** [comment]
Implemented in 5157636ca7854f036da84d24f82c9a5833ac1fa3. Released in 0.6.2

**Comment by Chocobozzz** [comment]
Thanks @mrlika!
