### ISSUE TITLE
Plyr player integration

### ISSUE THREAD

**Issue by supersh86** [Novage/p2p-media-loader#88]
Hello. It would be great if you created integration with plyr player. At the moment he is very popular.
https://github.com/sampotts/plyr

**Comment by mrlika** [comment]
Hi! We will investigate it!

**Comment by mrlika** [comment]
Quick question: does it have Hls.js or Shaka integrations?

**Comment by supersh86** [comment]
Если можно отвечу на русском.
Да есть интеграция с HLSJS
Я изучил разные плееры и пришел к выводу что у плура с вашим скриптом проблемы.
Вот мой конфиг на чистый плур и вас.

```
document.addEventListener('DOMContentLoaded', () => {
	const source = 'video.php?vid=<?php echo $_GET["vid"] . '&id=1' ?>';
	const video = document.querySelector('video');
	p2pConfig={
  segments:{
    forwardSegmentCount:40,
    swarmId:'<?php echo $_GET["vid"] ?>'
  },
  loader:{
    simultaneousHttpDownloads:1,

  }
};
var p2p = new p2pml.hlsjs.Engine(p2pConfig);
	const player = new Plyr(video, {captions: {active: true, update: true, language: 'en'}});

	if (!Hls.isSupported()) {
		video.src = source;
	} else {
		  var hls = new Hls({
            loader: p2p.createLoaderClass()

  })
		hls.loadSource(source);
		hls.attachMedia(video);
		window.hls = hls;
		player.on('languagechange', () => {
			setTimeout(() => hls.subtitleTrack = player.currentTrack, 50);
		});
	}
	window.player = player;
});
```
У меня случаются время от времени фризы с плеером. Подтормашивания, хотя если судить по буферизации и загрузке, там все ок. Около минуты прелоада. С чем связанно не пойму, но в том же DP плеере проблем нет.

**Comment by mrlika** [comment]
You are right - integration with Plyr is not required because it already works with it via Hls instance.

Check a very similar example of integration with DPlayer: https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-hlsjs/demo/dplayer.html

Freezes happen most likely because of `liveSyncDurationCount` that is defaults to `3` in `Hls.js`. Change it to a bigger value:

```javascript
const hls = new Hls({
   liveSyncDurationCount: 7, // To have at least 7 segments in queue
   loader: engine.createLoaderClass()
});
```

Having only 3 segments ahead of current play position will result in bad P2P ratio.

**Comment by mrlika** [comment]
Samples in this pull request https://github.com/Novage/p2p-media-loader/pull/90. We will add Plyr to our online demo soon.

**Comment by mrlika** [comment]
Added to demo: https://novage.com.ua/p2p-media-loader/demo.html?url=https%3A%2F%2Fwowza.peer5.com%2Flive%2Fsmil%3Abbb_abr.smil%2Fplaylist.m3u8&type=plyr
