### ISSUE TITLE
Subtitle no diplay with JWplay 8.5.6

### ISSUE THREAD

**Issue by davidtini21** [Novage/p2p-media-loader#9]
i tried with new jwplayer (8.5.6) but can't display SUB . i see CC button .

**Comment by mrlika** [comment]
We use [hola-jwplayer-hlsjs](https://github.com/hola/jwplayer-hlsjs) to run hls.js engine in JWPlayer. Probably it doesn't support the subtitles.

Can you test if JWPlayer supports subtitle via hola-jwplayer-hlsjs but without enabling P2P Media Loader or share with us stream URL so we can test it ourselves?

**Comment by davidtini21** [comment]
Seem no . i tried with 8.0 jw and it working ok . 
but 8.5 it not .

**Comment by mrlika** [comment]
Looks like API changed and [hola-jwplayer-hlsjs](https://github.com/hola/jwplayer-hlsjs) doesn't support subtitles in JWPlayer 8.5

**Comment by mrlika** [comment]
WebVTT subtitles referenced in HLS manifest work in JWPlayer. For example with this stream (time 07:40): https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8

Feel free to reopen the issue giving more details.
