### ISSUE TITLE
How to integrate with some third party player

### ISSUE THREAD

**Issue by quanghuy1288** [Novage/p2p-media-loader#91]
Our company using a DRM player from https://castlabs.com/ 
They using videojs and shaka player for web version
And using an SDK for Android and iOS.

How to integrate p2p-media-loader with their player?

**Comment by mrlika** [comment]
We integrate with video.js using one of hls.js plugins:

- example with videojs-hlsjs-plugin: https://cdn.streamroot.io/videojs-hlsjs-plugin/1/stable/videojs-hlsjs-plugin.js

- example with videojs-contrib-hls.js plugin: https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-hlsjs/demo/videojs-contrib-hlsjs.html

Here you can find implementations of functions for both plugins (
`initVideoJsContribHlsJsPlayer` and `initVideoJsHlsJsPlugin`) that do the integration: https://github.com/Novage/p2p-media-loader/blob/b33a214df3b5ed54b49d81e4513bd62e3c42c298/p2p-media-loader-hlsjs/lib/index.ts#L46

**Comment by quanghuy1288** [comment]
How can i use p2p-media-loader on some platform like: Android, Webos LG smartTV, Samsung Tizen smartTV?

**Comment by mrlika** [comment]
@quanghuy1288, currently only in a WebView component or some framework based on WebView like React Native - running HTML5 player with P2P script there.

Currently no native implementation for Android and iOS that require using native WebRTC implementation without JavaScript at all like:

- https://webrtc.org/native-code/android/
- https://webrtc.org/native-code/ios/
