### ISSUE TITLE
A completely way for tracking statistic like: Bandwidth, ccu 

### ISSUE THREAD

**Issue by quanghuy1288** [Novage/p2p-media-loader#93]
I thought about integrating it with our cdn. But have no idea how to tracking statistic for charging: bandwidth p2p, ccu, ...

Do @mrlika  have any idea?

**Comment by ckcr4lyf** [comment]
The `media-peer` class emits events when bytes are downloaded / uploaded, you can fork it to harvest these stats.

However it is unethical, in my opinion, to use an open source library and the bandwidth of the peers, and then charge them for it.

**Comment by quanghuy1288** [comment]
@ckcr4lyf  I do not think it is unethical. For high ccu, we must setup private STUN server. The charging is for cover the costs.

Thanks for your response.

**Comment by mrlika** [comment]
We run free WebTorrent tracker: https://tracker.novage.com.ua/stats.json

It handles up to 40k simultaneous peers and it costs us 3 EUR month. STUN server almost doesn't require resources comparing to the tracker server - you can run it on the same server. And you can use public STUN servers. STUN protocol alone doesn't disclosure private info and the site that a user is visiting.

The main idea is the infrastructure behind P2P traffic is almost free.

**Comment by mrlika** [comment]
The ideas are in this issue: https://github.com/Novage/wt-tracker/issues/13
