### ISSUE TITLE
work with videojs 7?

### ISSUE THREAD

**Issue by kyawswarthwin** [Novage/p2p-media-loader#95]
any example for videojs 7?
videojs/http-streaming.

**Comment by mrlika** [comment]
It works with videojs only through hls.js plugin. We don't plan to support built into videojs http-streaming playback engine - in overall its quality is not as good as hls.js or shaka playback engines.

Examples:
- the demo: http://novage.com.ua/p2p-media-loader/demo.html
- videojs-contrib-hlsjs plugin: https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-hlsjs/demo/videojs-contrib-hlsjs.html
- videojs-hlsjs plugin: https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-hlsjs/demo/videojs-hlsjs-plugin.html

**Comment by Phillipip** [comment]
It would be great if you would also support the new version. This reacts much faster with bad internet connections and switches much better to alternative resolutions.
