### ISSUE TITLE
geo or latency(ping) peering?

### ISSUE THREAD

**Issue by ranweb** [Novage/p2p-media-loader#96]
hi,
first of all - amazing implementation, well done!
i wanted to know if you plan or have already some kind of algorithm/method to choose the peers that are "closest" to you - either by Geoip method or Latency (ping measurement).

someone once told me that Peer5 have it in their implementation. i have no idea if that is true or not and was wondering if you have such a thing or consider to implement.

also - is it possible to add multiple HTTP sources? i think i saw with HOLA (spark player) that they use many multiple HTTP sources and cancel those that return 503 (i guess allowing them to maximize edge nodes). 

tnx!

**Comment by mrlika** [comment]
Hi,

I think that GeoIP peers targeting is best to implement in tracker. We use WebTorrent tracker protocol. Open-source implementations:
- [wt-tracker](https://github.com/Novage/wt-tracker) by @Novage
- [bittorrent-tracker](https://github.com/webtorrent/bittorrent-tracker) by @feross and @WebTorrent

HLS and MPEG-DASH protocols support multiple HTTP sources but as far as I know only for different representations (by quality, codecs, bitrate, resolution etc.) of a media stream. And it can not be used for load balancing or high availability via redundancy. 

But @Chocobozzz in [PeerTube](https://github.com/Chocobozzz/PeerTube) project implements multiple HTTP soruces using `segmentUrlBuilder` callback that allows to modify the segment URL before HTTP request. See [settings](https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-core#loader--new-hybridloadersettings) documentation.

**Comment by ranweb** [comment]
tnx for the answer. I think I found a "primitive" way to do it - I can use GeoIP for setting all traffic from one country to a specific url - serverA.example.com/video.mp4/index.m3u8 and all the traffic from other countries to another one like - serverB.example.com/video.mp4/index.m3u8 : if I understand correctly, even if i don't do geo balancing to the servers and even if both urls point to same server - i will have "two swarms" since there are actually 2 different torrents... right?

also - regarding the trackers. what does it mean if i list 2-3 trackers? does the script try the first and only if fails the second or does it announce to all 2-3 trackers simultaniously?

last question for today .- why is  httpUseRanges turned to False/off in the custom setup? is the custom setup your recommended setup for Live? (I saw that you have a special setup for VOD in the documentation) should i turn Httpuseranges to true?

**Comment by Vladislavik** [comment]
You can use different servers with files, located in different places/countries, and separate users from different countries by different swarmid or different trackers. Httpuseranges Set to true if your server work with ranges requests.

**Comment by mrlika** [comment]
If you configure few trackers - they will be used simultaneously for announce.
