### ISSUE TITLE
d/u info to btt

### ISSUE THREAD

**Issue by DenisFeedYT** [Novage/p2p-media-loader#98]
Is it possible to send download / upload info to the bt-tracker ?
sample code ?
Thx!

**Comment by mrlika** [comment]
Not possible without modification of source code

**Comment by DenisFeedYT** [comment]
ok,
can add as a feature ?

**Comment by mullerivan** [comment]
hi there , we  have that  solution already implemented  get a look at https://swarm.video/#/home

**Comment by ckcr4lyf** [comment]
@imarsv , commenting on every issue on an open source project is not an appropriate way to advertise whatever you are selling. Please delete those other comments and refrain from doing so in the fututre.
