### ISSUE TITLE
Segments are downloaded out of order (no matter peers are connected)

### ISSUE THREAD

**Issue by renatofrota** [Novage/p2p-media-loader#99]
Hello,

I have noticed (apparently started happening only recently) the segments are being downloaded out of order (from HTTP source).

This is visible at your demo, [using a unique swarm id](http://novage.com.ua/p2p-media-loader/demo.html?url=https%3A%2F%2Fwowza.peer5.com%2Flive%2Fsmil%3Abbb_abr.smil%2Fplaylist.m3u8&type=clappr&swarm=AnyUniqueSwarmIdToPreventOtherPeers) (to prevent peers joining)

Example: chunklist has segments 100-120; player downloads 100, start playing, then it downloads non sequentially, like 101, 104, 105, 102, 108, 103, ... and playback freezes due to next segment pending download (most times, they're not even queued).

["Non-P2P" Clappr](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cHM6Ly93b3d6YS5wZWVyNS5jb20vbGl2ZS9zbWlsOmJiYl9hYnIuc21pbC9wbGF5bGlzdC5tM3U4JywKICBwb3N0ZXI6ICdodHRwczovL3VwbG9hZC53aWtpbWVkaWEub3JnL3dpa2lwZWRpYS9jb21tb25zL2EvYTcvQmlnX0J1Y2tfQnVubnlfdGh1bWJuYWlsX3ZsYy5wbmcnLAogIG11dGU6IHRydWUsCiAgaGVpZ2h0OiAzNjAsCiAgd2lkdGg6IDY0MAp9KTsKCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTsK) loads all the segments sequentially (from the same manifest URL).

Related to issue #51 ?

**Comment by mrlika** [comment]
Random HTTP download order is required for P2P network to function.

But there is an option to download segments sequentially if there are no peers:

httpDownloadProbabilitySkipIfNoPeers | Boolean | false | Don't download segments over HTTP randomly when there is no peers

Check the documentation: https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-core#hybridloader

**Comment by renatofrota** [comment]
Interesting option. IMO, that should be true by default - otherwise, it freezes very often (or stops playback, depending on the player).

Thank you
